-- Issue #58: 日報データ取り込み基盤とExcel／CSV取込

CREATE TABLE IF NOT EXISTS daily_report_import_mappings (
  daily_report_import_mapping_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  mapping_name VARCHAR(200) NOT NULL,
  source_type VARCHAR(16) NOT NULL DEFAULT 'excel',
  filename_pattern VARCHAR(255) NULL,
  sheet_pattern VARCHAR(255) NULL,
  header_row INT UNSIGNED NOT NULL DEFAULT 1,
  mapping_json JSON NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by_user_id BIGINT UNSIGNED NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_drim_source_active (source_type, is_active, is_deleted),
  CONSTRAINT fk_drim_user FOREIGN KEY (created_by_user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_report_import_batches (
  daily_report_import_batch_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_type VARCHAR(16) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'uploaded',
  target_year_month CHAR(7) NULL,
  mapping_template_id BIGINT UNSIGNED NULL,
  source_sender VARCHAR(320) NULL,
  source_subject VARCHAR(500) NULL,
  source_received_at DATETIME NULL,
  parser_name VARCHAR(100) NULL,
  parser_version VARCHAR(50) NULL,
  row_count INT UNSIGNED NOT NULL DEFAULT 0,
  valid_count INT UNSIGNED NOT NULL DEFAULT 0,
  warning_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  applied_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_summary TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  parsed_at DATETIME NULL,
  completed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancelled_by_user_id BIGINT UNSIGNED NULL,
  cancellation_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  extra_data JSON NULL,
  KEY idx_drib_status_created (status, created_at),
  KEY idx_drib_ym (target_year_month),
  KEY idx_drib_mapping (mapping_template_id),
  CONSTRAINT fk_drib_mapping FOREIGN KEY (mapping_template_id) REFERENCES daily_report_import_mappings (daily_report_import_mapping_id),
  CONSTRAINT fk_drib_created_user FOREIGN KEY (created_by_user_id) REFERENCES users (user_id),
  CONSTRAINT fk_drib_cancelled_user FOREIGN KEY (cancelled_by_user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_report_import_files (
  daily_report_import_file_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  daily_report_import_batch_id BIGINT UNSIGNED NOT NULL,
  parent_file_id BIGINT UNSIGNED NULL,
  original_filename VARCHAR(500) NOT NULL,
  stored_filename VARCHAR(255) NOT NULL,
  storage_path VARCHAR(1000) NOT NULL,
  mime_type VARCHAR(200) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  sheet_names JSON NULL,
  retention_until DATE NOT NULL,
  deleted_at DATETIME NULL,
  deleted_by_user_id BIGINT UNSIGNED NULL,
  deletion_reason VARCHAR(500) NULL,
  replaced_by_file_id BIGINT UNSIGNED NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_drif_batch (daily_report_import_batch_id),
  KEY idx_drif_hash (sha256),
  KEY idx_drif_retention (retention_until, is_active),
  CONSTRAINT fk_drif_batch FOREIGN KEY (daily_report_import_batch_id) REFERENCES daily_report_import_batches (daily_report_import_batch_id),
  CONSTRAINT fk_drif_parent FOREIGN KEY (parent_file_id) REFERENCES daily_report_import_files (daily_report_import_file_id),
  CONSTRAINT fk_drif_deleted_user FOREIGN KEY (deleted_by_user_id) REFERENCES users (user_id),
  CONSTRAINT fk_drif_replacement FOREIGN KEY (replaced_by_file_id) REFERENCES daily_report_import_files (daily_report_import_file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_report_import_rows (
  daily_report_import_row_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  daily_report_import_batch_id BIGINT UNSIGNED NOT NULL,
  source_file_id BIGINT UNSIGNED NOT NULL,
  source_sheet VARCHAR(255) NULL,
  source_row_number INT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  raw_data JSON NOT NULL,
  parsed_data JSON NULL,
  reviewed_data JSON NULL,
  validation_errors JSON NULL,
  validation_warnings JSON NULL,
  matched_project_id BIGINT UNSIGNED NULL,
  matched_partner_id BIGINT UNSIGNED NULL,
  match_reason VARCHAR(500) NULL,
  row_fingerprint CHAR(64) NOT NULL,
  daily_report_id BIGINT UNSIGNED NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  applied_by_user_id BIGINT UNSIGNED NULL,
  applied_at DATETIME NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  extra_data JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_drir_batch_status (daily_report_import_batch_id, status),
  KEY idx_drir_fingerprint (row_fingerprint),
  KEY idx_drir_report (daily_report_id),
  CONSTRAINT fk_drir_batch FOREIGN KEY (daily_report_import_batch_id) REFERENCES daily_report_import_batches (daily_report_import_batch_id),
  CONSTRAINT fk_drir_file FOREIGN KEY (source_file_id) REFERENCES daily_report_import_files (daily_report_import_file_id),
  CONSTRAINT fk_drir_project FOREIGN KEY (matched_project_id) REFERENCES projects (project_id),
  CONSTRAINT fk_drir_partner FOREIGN KEY (matched_partner_id) REFERENCES partners (partner_id),
  CONSTRAINT fk_drir_report FOREIGN KEY (daily_report_id) REFERENCES daily_reports (daily_report_id),
  CONSTRAINT fk_drir_reviewed_user FOREIGN KEY (reviewed_by_user_id) REFERENCES users (user_id),
  CONSTRAINT fk_drir_applied_user FOREIGN KEY (applied_by_user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_report_import_audit_logs (
  daily_report_import_audit_log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  daily_report_import_batch_id BIGINT UNSIGNED NOT NULL,
  daily_report_import_file_id BIGINT UNSIGNED NULL,
  daily_report_import_row_id BIGINT UNSIGNED NULL,
  action_code VARCHAR(64) NOT NULL,
  before_data JSON NULL,
  after_data JSON NULL,
  reason VARCHAR(500) NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  acted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_dria_batch_time (daily_report_import_batch_id, acted_at),
  CONSTRAINT fk_dria_batch FOREIGN KEY (daily_report_import_batch_id) REFERENCES daily_report_import_batches (daily_report_import_batch_id),
  CONSTRAINT fk_dria_file FOREIGN KEY (daily_report_import_file_id) REFERENCES daily_report_import_files (daily_report_import_file_id),
  CONSTRAINT fk_dria_row FOREIGN KEY (daily_report_import_row_id) REFERENCES daily_report_import_rows (daily_report_import_row_id),
  CONSTRAINT fk_dria_user FOREIGN KEY (actor_user_id) REFERENCES users (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
