const express = require('express');
const fs = require('fs');
const { getPool, query } = require('../db');
const { requireAuth, requireRole } = require('../middleware/auth');
const { ensureCycles } = require('./cash_management');
const { PDF_DIR, writePdf } = require('../services/settlement_pdf');

const router = express.Router();
router.use(requireAuth);
const SYSTEM_TAX_RATE = 0.1;
const roles = (req) => new Set(req.session.user?.roles || []);
const has = (req, values) => values.some((v) => roles(req).has(v));
const asMoney = (value) => Math.round(Number(value || 0) * 100) / 100;
const effective = (row, kind) => Number(kind === 'invoice' ? (row.override_billing_amount ?? row.calculated_billing_amount ?? 0) : (row.override_payment_amount ?? row.calculated_payment_amount ?? 0));
const tableFor = (kind) => kind === 'invoice' ? 'invoices' : 'payments';
const idFor = (kind) => kind === 'invoice' ? 'invoice_id' : 'payment_id';

function validKind(kind) { return ['invoice', 'payment'].includes(kind); }
function rounding(amount, mode) { return mode === 'ceil' ? Math.ceil(amount) : mode === 'round' ? Math.round(amount) : Math.floor(amount); }
function json(value) { if (!value) return {}; return typeof value === 'string' ? JSON.parse(value) : value; }

async function checkMonthlyApprovals(conn, reports, ym) {
  const projects = [...new Set(reports.map((r) => r.project_id).filter(Boolean))];
  for (const projectId of projects) {
    const [rows] = await conn.query(`SELECT monthly_approval_id, snapshot_data FROM daily_report_monthly_approvals WHERE project_id=? AND target_year_month=? AND status='approved' ORDER BY approval_version DESC LIMIT 1`, [projectId, ym]);
    if (!rows.length) throw new Error('月次承認済みの日報だけを請求・支払の根拠にできます');
  }
}

async function insertLines(conn, kind, settlementId, lines) {
  for (const line of lines) {
    await conn.query(`INSERT INTO settlement_lines (settlement_type,settlement_id,line_type,source_type,source_id,project_id,daily_report_id,item_name,quantity,unit_price,amount,tax_category,reason,snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, [kind, settlementId, line.line_type, line.source_type, line.source_id || null, line.project_id || null, line.daily_report_id || null, line.item_name, line.quantity ?? 1, line.unit_price ?? line.amount, line.amount, line.tax_category || 'taxable', line.reason || null, JSON.stringify(line.snapshot || {})]);
  }
}

async function addCompatibilityLines(conn, kind, id, lines) {
  if (kind === 'invoice') {
    for (const line of lines) await conn.query(`INSERT INTO invoice_details (invoice_id,price_name,unit_price,quantity,amount,is_adjustment_row,extra_data) VALUES (?,?,?,?,?,?,?)`, [id,line.item_name,line.unit_price ?? line.amount,line.quantity ?? 1,line.amount,line.line_type === 'adjustment' ? 1 : 0,JSON.stringify({ source_type: line.source_type, tax_category: line.tax_category, reason: line.reason || null })]);
  } else {
    for (const line of lines) await conn.query(`INSERT INTO payment_details (payment_id,detail_type,item_name,unit_price,quantity,amount,extra_data) VALUES (?,?,?,?,?,?,?)`, [id, line.line_type === 'work' ? 'work_item' : line.line_type === 'adjustment' ? 'adjustment_item' : 'deduction_item', line.item_name,line.unit_price ?? line.amount,line.quantity ?? 1,line.amount,JSON.stringify({ source_type: line.source_type, tax_category: line.tax_category, reason: line.reason || null })]);
  }
}

async function applicableRules(conn, partnerId, ym) {
  const [rows] = await conn.query(`SELECT r.* FROM settlement_deduction_rules r WHERE r.is_active=1 AND r.valid_from <= ? AND (r.valid_to IS NULL OR r.valid_to >= ?) AND (r.scope='common' OR r.partner_id=?) ORDER BY r.rule_code, CASE WHEN r.scope='partner' THEN 0 ELSE 1 END, r.valid_from DESC`, [`${ym}-31`, `${ym}-01`, partnerId]);
  const used = new Set();
  return rows.filter((r) => !used.has(r.rule_code) && used.add(r.rule_code));
}

router.get('/settings/deduction-rules', requireRole('admin','soumu'), async (_req,res) => {
  try { return res.json({ok:true,rules:await query(`SELECT r.*,p.partner_name FROM settlement_deduction_rules r LEFT JOIN partners p ON p.partner_id=r.partner_id ORDER BY r.rule_code,r.valid_from DESC`)}); }
  catch (_err) { return res.status(500).json({ok:false,message:'控除ルールの取得に失敗しました'}); }
});
router.post('/settings/deduction-rules', requireRole('admin','soumu'), async (req,res) => {
  const b=req.body||{}; if(!String(b.rule_code||'').trim()||!String(b.display_name||'').trim()||!b.valid_from||!Number.isFinite(Number(b.amount))) return res.status(400).json({ok:false,message:'ルールコード、名称、金額、適用開始日は必須です'});
  try { const [result]=await getPool().query(`INSERT INTO settlement_deduction_rules (rule_code,scope,partner_id,display_name,amount,tax_category,valid_from,valid_to,is_active) VALUES (?,?,?,?,?,?,?,?,?)`,[String(b.rule_code).trim(),b.scope==='partner'?'partner':'common',b.scope==='partner'?Number(b.partner_id):null,String(b.display_name).trim(),Number(b.amount),b.tax_category||'taxable',b.valid_from,b.valid_to||null,b.is_active===false?0:1]); return res.status(201).json({ok:true,settlement_deduction_rule_id:result.insertId}); }
  catch(err){return res.status(400).json({ok:false,message:err.message});}
});
router.put('/settings/company/:companyId', requireRole('admin','soumu'), async(req,res)=>{const b=req.body||{};try{await getPool().query(`INSERT INTO company_invoice_settings (company_id,display_mode,tax_rate,tax_rounding) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE display_mode=VALUES(display_mode),tax_rate=VALUES(tax_rate),tax_rounding=VALUES(tax_rounding)`,[Number(req.params.companyId),b.display_mode==='project_aggregated'?'project_aggregated':'detailed',b.tax_rate??null,b.tax_rounding||'floor']);return res.json({ok:true});}catch(err){return res.status(400).json({ok:false,message:err.message});}});
router.put('/settings/project/:projectId', requireRole('admin','soumu'), async(req,res)=>{const b=req.body||{};try{await getPool().query(`INSERT INTO project_invoice_settings (project_id,tax_rate,tax_rounding) VALUES (?,?,?) ON DUPLICATE KEY UPDATE tax_rate=VALUES(tax_rate),tax_rounding=VALUES(tax_rounding)`,[Number(req.params.projectId),b.tax_rate??null,b.tax_rounding||null]);return res.json({ok:true});}catch(err){return res.status(400).json({ok:false,message:err.message});}});
router.put('/settings/project/:projectId/reviewers', requireRole('admin','soumu'), async(req,res)=>{const ids=Array.isArray(req.body?.user_ids)?req.body.user_ids.map(Number).filter(Boolean):[];const conn=await getPool().getConnection();try{await conn.beginTransaction();await conn.query('DELETE FROM project_settlement_reviewers WHERE project_id=?',[Number(req.params.projectId)]);for(const userId of ids)await conn.query(`INSERT INTO project_settlement_reviewers (project_id,user_id) SELECT ?,user_id FROM users WHERE user_id=? AND is_deleted=0`,[Number(req.params.projectId),userId]);await conn.commit();return res.json({ok:true});}catch(err){await conn.rollback();return res.status(400).json({ok:false,message:err.message});}finally{conn.release();}});

router.post('/:kind/drafts', requireRole('admin', 'soumu'), async (req, res) => {
  const kind = req.params.kind;
  if (!validKind(kind)) return res.status(404).json({ ok:false, message:'対象が不正です' });
  const b = req.body || {}; const ym = String(b.target_year_month || ''); const entityId = Number(kind === 'invoice' ? b.company_id : b.partner_id);
  const ids = Array.isArray(b.daily_report_ids) ? b.daily_report_ids.map(Number).filter(Boolean) : [];
  if (!/^\d{4}-\d{2}$/.test(ym) || !entityId || !ids.length) return res.status(400).json({ok:false,message:'対象年月、相手先、月次承認済み日報は必須です'});
  const pool=getPool(); const conn=await pool.getConnection();
  try {
    await conn.beginTransaction();
    const [reports] = await conn.query(`SELECT d.*,pr.project_name,pr.company_id AS project_company_id FROM daily_reports d LEFT JOIN projects pr ON pr.project_id=d.project_id WHERE d.daily_report_id IN (${ids.map(()=>'?').join(',')}) AND d.is_deleted=0 AND d.target_year_month=? AND d.status='approved' AND ${kind === 'invoice' ? 'd.company_id=? AND d.billing_status=\'none\'' : 'd.partner_id=? AND d.payment_status=\'none\''} FOR UPDATE`, [...ids, ym, entityId]);
    if (reports.length !== ids.length) throw new Error('対象日報には承認済みでない、または既に確定対象となったものが含まれます');
    await checkMonthlyApprovals(conn, reports, ym);
    const workLines = reports.map((r) => ({ line_type:'work',source_type:'daily_report',source_id:r.daily_report_id,project_id:r.project_id,daily_report_id:r.daily_report_id,item_name:`${r.project_name || '案件'} ${String(r.work_date).slice(0,10)}`,quantity:1,unit_price:effective(r,kind),amount:effective(r,kind),tax_category:'taxable',snapshot:r }));
    const manual = Array.isArray(b.adjustments) ? b.adjustments.map((x) => ({ line_type:'adjustment',source_type:'manual_adjustment',item_name:String(x.item_name || '調整'),quantity:1,unit_price:asMoney(x.amount),amount:asMoney(x.amount),tax_category:x.tax_category || 'taxable',reason:String(x.reason || '').trim() || null,snapshot:x })) : [];
    if (manual.some((x)=>x.amount < 0 && !x.reason)) throw new Error('負額調整には理由が必要です');
    const lines = [...workLines, ...manual];
    let settlementId;
    if (kind === 'invoice') {
      const [company] = await conn.query('SELECT company_name FROM companies WHERE company_id=? AND is_deleted=0',[entityId]); if (!company.length) throw new Error('企業が見つかりません');
      const [result] = await conn.query(`INSERT INTO invoices (company_id,target_year_month,closing_date,invoice_status,settlement_status,subtotal_amount,adjustment_amount,taxable_amount,tax_amount,total_amount,extra_data) VALUES (?,?,?,'draft','draft',0,0,0,0,0,?)`,[entityId,ym,String(b.closing_date || 'end'),JSON.stringify({ draft_source:'settlement' })]); settlementId=result.insertId;
    } else {
      const [partner] = await conn.query('SELECT partner_name,payment_output_code FROM partners WHERE partner_id=? AND is_deleted=0',[entityId]); if (!partner.length) throw new Error('パートナーが見つかりません');
      const [result] = await conn.query(`INSERT INTO payments (partner_id,target_year_month,closing_date,payment_status,settlement_status,gross_amount,final_transfer_amount,payment_output_code,extra_data) VALUES (?,?,?,'draft','draft',0,0,?,?)`,[entityId,ym,String(b.closing_date || 'end'),partner[0].payment_output_code || null,JSON.stringify({ draft_source:'settlement', issue_salary_statement: Boolean(b.issue_salary_statement) })]); settlementId=result.insertId;
    }
    await insertLines(conn,kind,settlementId,lines); await addCompatibilityLines(conn,kind,settlementId,lines);
    for (const r of reports) await conn.query(kind === 'invoice' ? 'INSERT INTO invoice_daily_reports (invoice_id,daily_report_id) VALUES (?,?)' : 'INSERT INTO payment_daily_reports (payment_id,daily_report_id) VALUES (?,?)',[settlementId,r.daily_report_id]);
    await conn.query(`INSERT INTO settlement_workflows (settlement_type,settlement_id,drafted_by_user_id) VALUES (?,?,?)`,[kind,settlementId,req.session.user.user_id]);
    await conn.commit(); return res.status(201).json({ok:true, settlement_id:settlementId, status:'draft'});
  } catch(err) { await conn.rollback(); return res.status(400).json({ok:false,message:err.message}); } finally { conn.release(); }
});

router.post('/:kind/:id/sales-review', requireRole('admin','sales'), async (req,res) => {
  const kind=req.params.kind, id=Number(req.params.id); if(!validKind(kind)) return res.status(404).end(); const conn=await getPool().getConnection();
  try { await conn.beginTransaction(); const [wf]=await conn.query(`SELECT * FROM settlement_workflows WHERE settlement_type=? AND settlement_id=? FOR UPDATE`,[kind,id]); if(!wf.length || wf[0].status!=='draft') throw new Error('下書き状態のものだけ営業確認できます');
    const links=await conn.query(kind==='invoice'?`SELECT d.project_id FROM invoice_daily_reports l JOIN daily_reports d ON d.daily_report_id=l.daily_report_id WHERE l.invoice_id=?`:`SELECT d.project_id FROM payment_daily_reports l JOIN daily_reports d ON d.daily_report_id=l.daily_report_id WHERE l.payment_id=?`,[id]);
    const projectIds=[...new Set(links[0].map(x=>x.project_id).filter(Boolean))]; const actor=req.session.user.user_id;
    if (!roles(req).has('admin')) for(const projectId of projectIds){const [reviewers]=await conn.query('SELECT user_id FROM project_settlement_reviewers WHERE project_id=?',[projectId]); if(!reviewers.some(x=>Number(x.user_id)===Number(actor))) throw new Error('担当営業者だけが確認できます。案件に営業確認者を設定してください');}
    await conn.query(`UPDATE settlement_workflows SET status='sales_reviewed',sales_reviewed_by_user_id=?,sales_reviewed_at=CURRENT_TIMESTAMP WHERE settlement_workflow_id=?`,[actor,wf[0].settlement_workflow_id]); await conn.query(`UPDATE ${tableFor(kind)} SET settlement_status='sales_reviewed' WHERE ${idFor(kind)}=?`,[id]); await conn.commit(); return res.json({ok:true,status:'sales_reviewed'});
  } catch(err){await conn.rollback();return res.status(400).json({ok:false,message:err.message});} finally{conn.release();}
});

async function nextDocumentNumber(conn, type, year) { await conn.query(`INSERT INTO settlement_document_sequences (document_type,document_year,last_number) VALUES (?,?,1) ON DUPLICATE KEY UPDATE last_number=LAST_INSERT_ID(last_number+1)`,[type,year]); const [rows]=await conn.query('SELECT last_number FROM settlement_document_sequences WHERE document_type=? AND document_year=?',[type,year]); return `${type.toUpperCase()}-${year}-${String(rows[0].last_number).padStart(5,'0')}`; }

router.post('/:kind/:id/finalize', requireRole('admin','executive'), async (req,res) => {
  const kind=req.params.kind,id=Number(req.params.id); if(!validKind(kind)) return res.status(404).end(); const b=req.body||{}; const conn=await getPool().getConnection(); const generated=[];
  try { await conn.beginTransaction(); const [headerRows]=await conn.query(`SELECT s.*, ${kind==='invoice'?'c.company_name':'p.partner_name'} FROM ${tableFor(kind)} s LEFT JOIN ${kind==='invoice'?'companies c ON c.company_id=s.company_id':'partners p ON p.partner_id=s.partner_id'} WHERE s.${idFor(kind)}=? FOR UPDATE`,[id]); const header=headerRows[0]; if(!header) throw new Error('対象が見つかりません'); const [wf]=await conn.query('SELECT * FROM settlement_workflows WHERE settlement_type=? AND settlement_id=? FOR UPDATE',[kind,id]); if(!wf.length || wf[0].status!=='sales_reviewed') throw new Error('営業確認済みの下書きだけ最終確定できます');
    const [lines]=await conn.query('SELECT * FROM settlement_lines WHERE settlement_type=? AND settlement_id=? ORDER BY settlement_line_id',[kind,id]); let finalLines=lines.map(x=>({...x,amount:Number(x.amount),unit_price:Number(x.unit_price),quantity:Number(x.quantity)}));
    let pdfLines = finalLines;
    if(kind==='invoice'){ const [setting]=await conn.query('SELECT * FROM company_invoice_settings WHERE company_id=?',[header.company_id]); const projects=[...new Set(finalLines.map(x=>x.project_id).filter(Boolean))]; let taxRate=setting[0]?.tax_rate ?? SYSTEM_TAX_RATE, taxMode=setting[0]?.tax_rounding ?? 'floor'; if(projects.length===1){const [ps]=await conn.query('SELECT * FROM project_invoice_settings WHERE project_id=?',[projects[0]]); taxRate=ps[0]?.tax_rate ?? taxRate; taxMode=ps[0]?.tax_rounding ?? taxMode;} const taxable=finalLines.filter(x=>x.tax_category==='taxable').reduce((n,x)=>n+x.amount,0); const tax=rounding(taxable*Number(taxRate),taxMode); const total=asMoney(finalLines.reduce((n,x)=>n+x.amount,0)+tax); if(setting[0]?.display_mode === 'project_aggregated'){const grouped=new Map();for(const line of finalLines){const key=line.project_id||`other:${line.line_type}`;const old=grouped.get(key)||{...line,item_name:line.project_id?`案件 #${line.project_id}`:line.item_name,quantity:0,unit_price:0,amount:0};old.quantity+=Number(line.quantity||1);old.amount+=Number(line.amount);grouped.set(key,old);}pdfLines=[...grouped.values()];} await conn.query(`UPDATE invoices SET subtotal_amount=?,adjustment_amount=?,taxable_amount=?,tax_amount=?,total_amount=?,invoice_status='finalized',settlement_status='finalized',finalized_snapshot=? WHERE invoice_id=?`,[finalLines.filter(x=>x.line_type==='work').reduce((n,x)=>n+x.amount,0),finalLines.filter(x=>x.line_type==='adjustment').reduce((n,x)=>n+x.amount,0),taxable,tax,total,JSON.stringify({header,lines:finalLines,display_lines:pdfLines,tax_rate:taxRate,tax_rounding:taxMode}),id]); header.total_amount=total;
    } else { const gross=finalLines.filter(x=>x.line_type==='work'||x.line_type==='adjustment').reduce((n,x)=>n+x.amount,0); const rules=await applicableRules(conn,header.partner_id,header.target_year_month); const [carries]=await conn.query(`SELECT * FROM settlement_carry_forwards WHERE partner_id=? AND status='open' FOR UPDATE`,[header.partner_id]); const [advances]=await conn.query(`SELECT ar.advance_record_id, ar.advance_amount-COALESCE(SUM(a.amount),0) remaining FROM advance_records ar JOIN cash_schedules cs ON cs.cash_schedule_id=ar.cash_schedule_id AND cs.status='executed' LEFT JOIN advance_payment_allocations a ON a.advance_record_id=ar.advance_record_id WHERE ar.partner_id=? AND ar.status='executed' GROUP BY ar.advance_record_id,ar.advance_amount HAVING remaining>0 FOR UPDATE`,[header.partner_id]); const candidates=[...carries.map(x=>({type:'carry',row:x,name:x.item_name,amount:Number(x.remaining_amount),tax:x.tax_category})),...advances.map(x=>({type:'advance',row:x,name:'前払控除',amount:Number(x.remaining),tax:'non_taxable'})),...rules.map(x=>({type:'rule',row:x,name:x.display_name,amount:Number(x.amount),tax:x.tax_category}))]; let available=Math.max(0,gross); for(const c of candidates){const applied=Math.min(available,c.amount);if(applied>0){const line={line_type:c.type==='advance'?'advance':c.type==='carry'?'carry_forward':'deduction',source_type:c.type,source_id:c.type==='rule'?c.row.settlement_deduction_rule_id:c.type==='advance'?c.row.advance_record_id:c.row.settlement_carry_forward_id,item_name:c.name,quantity:1,unit_price:-applied,amount:-applied,tax_category:c.tax,snapshot:c.row}; finalLines.push(line); await insertLines(conn,kind,id,[line]); await addCompatibilityLines(conn,kind,id,[line]); if(c.type==='carry'){await conn.query(`UPDATE settlement_carry_forwards SET remaining_amount=remaining_amount-?,status=IF(remaining_amount-?<=0,'settled','open') WHERE settlement_carry_forward_id=?`,[applied,applied,c.row.settlement_carry_forward_id]);} if(c.type==='advance') await conn.query('INSERT INTO advance_payment_allocations (advance_record_id,payment_id,amount) VALUES (?,?,?)',[c.row.advance_record_id,id,applied]);} const remainder=c.amount-applied;if(remainder>0){if(c.type==='carry'){/* existing carry remains */}else{const lineId=null; await conn.query(`INSERT INTO settlement_carry_forwards (partner_id,source_payment_id,source_line_id,item_name,original_amount,remaining_amount,tax_category) VALUES (?,?,?,?,?,?,?)`,[header.partner_id,id,lineId,c.name,remainder,remainder,c.tax]);}} available-=applied;}
      const final=asMoney(available); await conn.query(`UPDATE payments SET gross_amount=?,advance_deduction_amount=?,office_fee_amount=?,safety_fee_amount=?,final_transfer_amount=?,payment_status='finalized',settlement_status='finalized',finalized_snapshot=? WHERE payment_id=?`,[gross,finalLines.filter(x=>x.line_type==='advance').reduce((n,x)=>n+Math.abs(x.amount),0),finalLines.filter(x=>x.item_name==='事務手数料').reduce((n,x)=>n+Math.abs(x.amount),0),finalLines.filter(x=>x.item_name==='安全協力会費').reduce((n,x)=>n+Math.abs(x.amount),0),final,JSON.stringify({header,lines:finalLines}),id]); header.total_amount=final;
    }
    const cycleId=Number(b.cash_cycle_id); if(!cycleId) throw new Error('最終確定には入出金管理回を指定してください'); const [cycles]=await conn.query('SELECT * FROM cash_cycles WHERE cash_cycle_id=? FOR UPDATE',[cycleId]); if(!cycles.length) throw new Error('入出金管理回が見つかりません'); if(Number(header.total_amount)>0) await conn.query(`INSERT INTO cash_schedules (cash_cycle_id,direction,source_type,source_id,company_id,partner_id,counterparty_name,title,amount,scheduled_date,snapshot_json,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[cycleId,kind==='invoice'?'incoming':'outgoing',kind,id,header.company_id||null,header.partner_id||null,header.company_name||header.partner_name,kind==='invoice'?'請求入金':'通常支払',header.total_amount,kind==='invoice'?cycles[0].planned_incoming_date:cycles[0].planned_outgoing_date,JSON.stringify({settlement_type:kind,settlement_id:id,total_amount:header.total_amount}),req.session.user.user_id]);
    const types=kind==='invoice'?['invoice','invoice_summary']:['payment_statement', ...(json(header.extra_data).issue_salary_statement?['salary_statement']:[])]; const year=Number(String(header.target_year_month).slice(0,4)); for(const type of types){const number=await nextDocumentNumber(conn,type,year); const document={settlement_type:kind,document_type:type,document_number:number,issued_date:new Date().toISOString().slice(0,10),target_year_month:header.target_year_month,total_amount:header.total_amount,company_name:header.company_name,partner_name:header.partner_name}; const pdf=await writePdf(document,pdfLines); generated.push(pdf.absolutePath); await conn.query(`INSERT INTO settlement_documents (settlement_type,settlement_id,document_type,document_year,document_number,company_id,partner_id,file_path,snapshot_json) VALUES (?,?,?,?,?,?,?,?,?)`,[kind,id,type,year,number,header.company_id||null,header.partner_id||null,pdf.fileName,JSON.stringify({document,lines:pdfLines,internal_lines:finalLines})]);}
    await conn.query(`UPDATE settlement_workflows SET status='finalized',finalized_by_user_id=?,finalized_at=CURRENT_TIMESTAMP WHERE settlement_workflow_id=?`,[req.session.user.user_id,wf[0].settlement_workflow_id]); for(const l of finalLines.filter(x=>x.daily_report_id)) await conn.query(kind==='invoice'?`UPDATE daily_reports SET billing_status='billed' WHERE daily_report_id=?`:`UPDATE daily_reports SET payment_status='paid' WHERE daily_report_id=?`,[l.daily_report_id]); await conn.commit(); return res.json({ok:true,status:'finalized',total_amount:header.total_amount});
  } catch(err){await conn.rollback();for(const file of generated) fs.unlinkSync(file,{force:true});return res.status(400).json({ok:false,message:err.message});} finally {conn.release();}
});

router.post('/:kind/:id/cancel', requireRole('admin','executive'), async(req,res)=>{const kind=req.params.kind,id=Number(req.params.id),reason=String(req.body?.reason||'').trim();if(!validKind(kind))return res.status(404).end();if(!reason)return res.status(400).json({ok:false,message:'取消理由は必須です'});const conn=await getPool().getConnection();try{await conn.beginTransaction();const [wf]=await conn.query('SELECT * FROM settlement_workflows WHERE settlement_type=? AND settlement_id=? FOR UPDATE',[kind,id]);if(!wf.length||wf[0].status!=='finalized')throw new Error('最終確定済みのものだけ取消できます');await conn.query(`UPDATE cash_schedules SET status='cancelled',version=version+1 WHERE source_type=? AND source_id=? AND status IN ('planned','exported','held')`,[kind,id]);await conn.query(`UPDATE settlement_documents SET status='cancelled',cancelled_at=CURRENT_TIMESTAMP,cancelled_by_user_id=?,cancellation_reason=? WHERE settlement_type=? AND settlement_id=?`,[req.session.user.user_id,reason,kind,id]);await conn.query(`UPDATE settlement_workflows SET status='cancelled',cancelled_by_user_id=?,cancelled_at=CURRENT_TIMESTAMP,cancellation_reason=? WHERE settlement_workflow_id=?`,[req.session.user.user_id,reason,wf[0].settlement_workflow_id]);await conn.query(`UPDATE ${tableFor(kind)} SET settlement_status='cancelled',${kind==='invoice'?'invoice_status':'payment_status'}='cancelled' WHERE ${idFor(kind)}=?`,[id]);await conn.commit();return res.json({ok:true});}catch(err){await conn.rollback();return res.status(400).json({ok:false,message:err.message});}finally{conn.release();}});

router.get('/documents/:id/download', async(req,res)=>{try{const [docs]=await query('SELECT * FROM settlement_documents WHERE settlement_document_id=?',[Number(req.params.id)]);const doc=docs[0];if(!doc)return res.status(404).json({ok:false,message:'帳票が見つかりません'});if(roles(req).has('company')&&Number(req.session.user.company_id)!==Number(doc.company_id))return res.status(403).json({ok:false,message:'この帳票は閲覧できません'});if(roles(req).has('partner')&&Number(req.session.user.partner_id)!==Number(doc.partner_id))return res.status(403).json({ok:false,message:'この帳票は閲覧できません'});if(roles(req).has('company')&&!['invoice','invoice_summary'].includes(doc.document_type))return res.status(403).json({ok:false,message:'企業は請求書だけ閲覧できます'});if(roles(req).has('partner')&&!['payment_statement','salary_statement'].includes(doc.document_type))return res.status(403).json({ok:false,message:'パートナーは支払帳票だけ閲覧できます'});return res.download(require('path').join(PDF_DIR,doc.file_path),doc.file_path);}catch(err){return res.status(500).json({ok:false,message:'帳票の取得に失敗しました'});}});

router.get('/:kind/:id', async(req,res)=>{const kind=req.params.kind,id=Number(req.params.id);if(!validKind(kind))return res.status(404).end();try{const [header]=await query(`SELECT * FROM ${tableFor(kind)} WHERE ${idFor(kind)}=?`,[id]);if(!header)return res.status(404).json({ok:false,message:'対象が見つかりません'});const lines=await query('SELECT * FROM settlement_lines WHERE settlement_type=? AND settlement_id=? ORDER BY settlement_line_id',[kind,id]);const workflow=await query('SELECT * FROM settlement_workflows WHERE settlement_type=? AND settlement_id=?',[kind,id]);const documents=await query('SELECT settlement_document_id,document_type,document_number,status,issued_at FROM settlement_documents WHERE settlement_type=? AND settlement_id=?',[kind,id]);return res.json({ok:true,settlement:header,lines,workflow:workflow[0]||null,documents});}catch(err){return res.status(500).json({ok:false,message:'取得に失敗しました'});}});

module.exports = router;
