#!/usr/bin/env bash
# Links-System DB を別NASへ移すための論理バックアップと照合マニフェストを作成する。
# 実行前に、利用者の入力・締め・帳票発行を停止して書込みを止めること。
set -euo pipefail
export PATH="/mingw64/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

ROOT="$(cd "$(dirname "$0")/../" && pwd)"
cd "$ROOT"
umask 077

BACKUP_DIR="${1:-backups}"
mkdir -p "$BACKUP_DIR"

set -a
# shellcheck disable=SC1091
source .env 2>/dev/null || true
set +a

MYSQL_USER="${MYSQL_USER:-links}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-links_pass_change_me}"
MYSQL_DATABASE="${MYSQL_DATABASE:-${DB_NAME:-links_system}}"

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    openssl dgst -sha256 "$1" | awk '{print $NF}'
  fi
}

sha256_text() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
  else
    openssl dgst -sha256 | awk '{print $NF}'
  fi
}

scalar() {
  docker compose exec -T db mysql -N -B \
    -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" -e "$1"
}

STAMP="$(date +%Y%m%d_%H%M%S)"
DUMP_FILE="$BACKUP_DIR/links_${MYSQL_DATABASE}_${STAMP}.sql"
MANIFEST_FILE="${DUMP_FILE%.sql}.manifest"
SOURCE_GIT_COMMIT="$(git rev-parse HEAD 2>/dev/null || printf '%040d' 0)"

echo "DB ダンプを作成します: $DUMP_FILE"
docker compose exec -T db \
  mysqldump -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
  --single-transaction --routines --triggers --events \
  "${MYSQL_DATABASE}" > "$DUMP_FILE"

if [[ ! -s "$DUMP_FILE" ]]; then
  echo "エラー: ダンプが空です。" >&2
  exit 1
fi

MIGRATIONS="$(scalar 'SELECT COUNT(*) FROM schema_migrations')"
LATEST_MIGRATION="$(scalar 'SELECT filename FROM schema_migrations ORDER BY filename DESC LIMIT 1')"
COMPANIES="$(scalar 'SELECT COUNT(*) FROM companies')"
PARTNERS="$(scalar 'SELECT COUNT(*) FROM partners')"
BASE_PROJECTS="$(scalar 'SELECT COUNT(*) FROM base_projects')"
PROJECTS="$(scalar 'SELECT COUNT(*) FROM projects')"
PRICE_SETS="$(scalar 'SELECT COUNT(*) FROM price_sets')"
DAILY_REPORTS="$(scalar 'SELECT COUNT(*) FROM daily_reports')"
ADVANCE_PAYMENTS="$(scalar 'SELECT COUNT(*) FROM advance_payments')"
INVOICES="$(scalar 'SELECT COUNT(*) FROM invoices')"
PAYMENTS="$(scalar 'SELECT COUNT(*) FROM payments')"
ADMIN_USER_COUNT="$(scalar "SELECT COUNT(*) FROM users WHERE login_id = 'admin' AND is_deleted = 0")"
if [[ "$ADMIN_USER_COUNT" != "1" ]]; then
  echo "エラー: 有効な管理者 admin が1件ではありません（${ADMIN_USER_COUNT}件）。" >&2
  exit 1
fi
ADMIN_PASSWORD_HASH="$(scalar "SELECT password_hash FROM users WHERE login_id = 'admin' AND is_deleted = 0 LIMIT 1")"
ADMIN_PASSWORD_HASH_SHA256="$(printf '%s' "$ADMIN_PASSWORD_HASH" | sha256_text)"

cat > "$MANIFEST_FILE" <<EOF
# Links-System DB migration manifest. Generated by scripts/nas-db-export.sh.
FORMAT_VERSION=1
SOURCE_CREATED_AT=$(date -Iseconds)
SOURCE_GIT_COMMIT=${SOURCE_GIT_COMMIT}
DATABASE=${MYSQL_DATABASE}
DUMP_FILE=$(basename "$DUMP_FILE")
DUMP_SHA256=$(sha256 "$DUMP_FILE")
DUMP_BYTES=$(wc -c < "$DUMP_FILE" | tr -d '[:space:]')
MIGRATIONS=${MIGRATIONS}
LATEST_MIGRATION=${LATEST_MIGRATION}
COMPANIES=${COMPANIES}
PARTNERS=${PARTNERS}
BASE_PROJECTS=${BASE_PROJECTS}
PROJECTS=${PROJECTS}
PRICE_SETS=${PRICE_SETS}
DAILY_REPORTS=${DAILY_REPORTS}
ADVANCE_PAYMENTS=${ADVANCE_PAYMENTS}
INVOICES=${INVOICES}
PAYMENTS=${PAYMENTS}
ADMIN_USER_COUNT=${ADMIN_USER_COUNT}
ADMIN_PASSWORD_HASH_SHA256=${ADMIN_PASSWORD_HASH_SHA256}
EOF

chmod 600 "$DUMP_FILE" "$MANIFEST_FILE"
echo "作成完了: $DUMP_FILE"
echo "照合情報: $MANIFEST_FILE"
echo "SHA-256: $(sha256 "$DUMP_FILE")"
