(() => {
  const ui={
    async open(ctx){this.ctx=ctx;this.kit=window.LinksFeatureKit.createFeatureKit(ctx);this.ym=this.kit.currentYearMonth();await this.show();},
    money(v){return Math.round(Number(v||0)).toLocaleString('ja-JP');},
    status(v){return ({unplanned:'未作成',planned:'予定作成済み',executed:'実行済み',cancelled:'取消済み',exported:'CSV出力済み',held:'保留'}[v]||v||'-');},
    async show(message=''){
      this.ctx.renderLoading();const [groups,terms,projects]=await Promise.all([this.ctx.api(`/api/advances/groups?target_year_month=${encodeURIComponent(this.ym)}`),this.ctx.api('/api/advances/terms'),this.ctx.api('/api/projects')]);if(!groups.res.ok)return this.error(groups.data?.message);this.groups=groups.data.groups||[];this.projects=projects.data?.projects||[];
      const groupHtml=this.groups.map(group=>`<section class="advance-group" data-group="${group.group_code}"><div class="section-title-row"><div><h3>${this.ctx.escapeHtml(group.label)}</h3><p class="muted">支払予定日 ${this.ctx.escapeHtml(group.payment_date)}</p></div><div class="btn-row"><button class="btn" data-create-group="${group.group_code}">選択分の支払予定を作成・更新</button><button class="btn btn-secondary" data-export-group="${group.group_code}" data-cycle="${group.cash_cycle_id}">CSV出力</button></div></div><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>選択</th><th>締日</th><th>パートナー</th><th>案件</th><th>対象期間</th><th>対象日数</th><th>前払単価</th><th>自動計算額</th><th>前払額</th><th>手数料</th><th>変更理由</th><th>状態</th><th>操作</th></tr></thead><tbody>${group.rows.map(row=>{const locked=['executed','cancelled'].includes(row.status);return`<tr data-advance-row="${row.project_id}"><td><input type="checkbox" data-select ${locked?'disabled':''}></td><td>${row.closing_date==='end'?'末日':`${row.closing_date}日`}</td><td>${this.ctx.escapeHtml(row.partner_name||'-')}</td><td>#${row.project_id} ${this.ctx.escapeHtml(row.template_name||'')}</td><td>${row.period_start}〜${row.period_end}</td><td class="num">${row.work_days}日</td><td class="num">${this.money(row.unit_price)}円</td><td class="num">${this.money(row.calculated_amount)}円</td><td><input data-field="advance_amount" type="number" min="0" value="${Number(row.advance_amount)}" ${locked?'disabled':''}></td><td><input data-field="transfer_fee_amount" type="number" min="0" value="${Number(row.transfer_fee_amount||0)}" ${locked?'disabled':''}></td><td><input data-field="adjustment_reason" value="${this.ctx.escapeHtml(row.adjustment_reason||'')}" ${locked?'disabled':''}></td><td><span class="status-badge status-${row.status}">${this.status(row.cash_status||row.status)}</span></td><td>${row.status==='planned'?`<button class="btn btn-ghost btn-small" data-cancel="${row.advance_record_id}">取消</button>`:row.status==='executed'?`<button class="btn btn-ghost btn-small" data-reverse="${row.advance_record_id}">返金調整</button>`:''}</td></tr>`;}).join('')||'<tr><td colspan="13">このグループの前払対象案件はありません</td></tr>'}</tbody></table></div></section>`).join('');
      const termRows=(terms.data?.terms||[]).map(t=>`<tr><td>#${t.project_id}</td><td>${this.ctx.escapeHtml(t.company_name||'-')}</td><td>${this.ctx.escapeHtml(t.partner_name||'-')}</td><td>${String(t.valid_from).slice(0,10)}</td><td class="num">${this.money(t.unit_price)}円</td><td>${t.is_enabled?'有効':'無効'}</td></tr>`).join('');
      this.ctx.app.innerHTML=this.kit.shell('前払管理',`<section class="panel">${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}${this.kit.monthNavigatorHtml(this.ym,'advance-month')}<div class="section-title-row"><div><h3>締日別3グループ</h3><p class="muted">確認済み日報の対象日数×前払単価を初期値とします。増減と手数料入力には理由が必要です。</p></div><button id="add-term" class="btn btn-secondary">＋ 前払条件</button></div>${groupHtml}<details class="panel-sub"><summary>案件別の前払条件</summary><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>案件</th><th>企業</th><th>パートナー</th><th>適用開始</th><th>前払単価</th><th>状態</th></tr></thead><tbody>${termRows||'<tr><td colspan="6">条件がありません</td></tr>'}</tbody></table></div></details><div class="btn-row"><button id="open-cash" class="btn btn-ghost">入出金実績・CSV管理を開く</button></div></section><div id="advance-editor"></div>`,{wide:true});
      this.kit.bindShell();this.kit.bindMonthNavigator('advance-month',()=>this.ym,v=>{this.ym=v;},()=>this.show());document.querySelectorAll('[data-create-group]').forEach(b=>b.onclick=()=>this.createGroup(b.dataset.createGroup));document.querySelectorAll('[data-export-group]').forEach(b=>b.onclick=()=>this.exportCsv(Number(b.dataset.cycle),b.dataset.exportGroup));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>this.cancel(Number(b.dataset.cancel)));document.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>this.reversal(Number(b.dataset.reverse)));document.getElementById('add-term').onclick=()=>this.termEditor();document.getElementById('open-cash').onclick=()=>window.LinksCashManagement?.open(this.ctx);
    },
    async createGroup(code){const section=document.querySelector(`[data-group="${code}"]`),rows=[...section.querySelectorAll('[data-advance-row]')].filter(row=>row.querySelector('[data-select]')?.checked);if(!rows.length)return window.alert('支払予定を作成する案件を選択してください');const items=rows.map(row=>({project_id:Number(row.dataset.advanceRow),advance_amount:Number(row.querySelector('[data-field="advance_amount"]').value),transfer_fee_amount:Number(row.querySelector('[data-field="transfer_fee_amount"]').value),adjustment_reason:row.querySelector('[data-field="adjustment_reason"]').value.trim()}));const result=await this.ctx.api(`/api/advances/groups/${code}/records`,{method:'POST',body:JSON.stringify({target_year_month:this.ym,items})});if(!result.res.ok)return window.alert(result.data?.message||'前払予定の作成に失敗しました');this.show(`${result.data.payment_date} 支払分の予定を作成しました`);},
    async cancel(id){const reason=window.prompt('取消理由を入力してください','');if(!reason)return;const r=await this.ctx.api(`/api/advances/records/${id}/cancel`,{method:'POST',body:JSON.stringify({reason})});if(!r.res.ok)return window.alert(r.data?.message||'取消に失敗しました');this.show('前払予定を取消しました');},
    async exportCsv(cashCycleId,groupCode){try{const response=await fetch('/api/cash-management/exports',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({cash_cycle_id:cashCycleId,group_code:groupCode})});if(!response.ok){const data=await response.json();throw new Error(data.message||'CSV出力に失敗しました');}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`advance-${groupCode}-${this.ym}.csv`;a.click();URL.revokeObjectURL(url);this.show('選択グループのCSVを出力しました');}catch(error){window.alert(error.message);}},
    termEditor(){const options=this.projects.map(p=>`<option value="${p.project_id}">#${p.project_id} ${this.ctx.escapeHtml(p.company_name||'')} / ${this.ctx.escapeHtml(p.partner_name||'')}</option>`).join(''),editor=document.getElementById('advance-editor');editor.innerHTML=`<section class="panel"><h3>前払条件を追加</h3><form id="term-form" class="form-grid"><label>案件<select name="project_id">${options}</select></label><label>適用開始日<input name="valid_from" type="date" required></label><label>前払単価<input name="unit_price" type="number" min="0" required></label><label class="check-item"><input name="is_enabled" type="checkbox" checked><span>前払可</span></label><button class="btn">登録</button></form></section>`;document.getElementById('term-form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form);body.is_enabled=form.get('is_enabled')==='on';const r=await this.ctx.api('/api/advances/terms',{method:'POST',body:JSON.stringify(body)});if(!r.res.ok)return window.alert(r.data?.message||'登録に失敗しました');this.show('前払条件を登録しました');};},
    async reversal(id){const cycle=window.prompt('返金先の管理回IDを入力してください','');const amount=window.prompt('返金・訂正額を入力してください','');if(!cycle||!amount)return;const r=await this.ctx.api(`/api/advances/records/${id}/reversal`,{method:'POST',body:JSON.stringify({cash_cycle_id:Number(cycle),amount:Number(amount)})});if(!r.res.ok)return window.alert(r.data?.message||'返金調整に失敗しました');this.show('返金・訂正予定を作成しました');},
    error(message){this.ctx.app.innerHTML=this.kit.shell('前払管理',`<section class="panel"><p class="error">${this.ctx.escapeHtml(message||'前払情報を取得できませんでした')}</p></section>`);this.kit.bindShell();},
  };window.LinksAdvances=ui;
})();
