(() => {
  const status={draft:'事務作成中',sales_review:'営業確認中',reviewed:'管理者確定待ち',returned:'差戻し',finalized:'確定済み',approved:'確認済み',pending:'未確認',superseded:'旧担当'};
  const ui={
    async open(ctx,options={}){this.ctx=ctx;this.options=options;this.kit=window.LinksFeatureKit.createFeatureKit(ctx);this.roles=new Set(ctx.currentUser?.roles||[]);this.office=this.roles.has('admin')||this.roles.has('soumu');this.finalizer=this.roles.has('admin')||this.roles.has('executive');await this.list();},
    e(value){return this.ctx.escapeHtml(String(value??''));},money(value){return `${Number(value||0).toLocaleString()}円`;},
    async api(path,body){const result=await this.ctx.api(`/api/annual-closings${path}`,body===undefined?{}:{method:'POST',body:JSON.stringify(body)});if(!result.res.ok||!result.data?.ok)throw new Error(result.data?.message||'年度締めの取得に失敗しました');return result.data;},
    shell(title,html,back){this.ctx.app.innerHTML=this.kit.shell(title,`<section class="panel annual-screen">${html}<p id="annual-error" role="alert" class="error"></p></section>`,{wide:true,onBack:back});this.kit.bindShell({onBack:back});},
    async run(fn){try{await fn();}catch(error){const el=document.getElementById('annual-error');if(el)el.textContent=error.message;else window.alert(error.message);}},
    async list(){await this.run(async()=>{
      const data=await this.api('');this.settings=(await this.api('/settings')).settings;
      this.shell('年度締め・年間集計',`<h2>12月〜翌11月の年間集計</h2><p>11月末の保存帳票を固定します。通常の請求・支払・入出金予定は変更しません。</p><div class="btn-row">${this.office?'<button class="btn" id="annual-new">年度の集計を作成</button>':''}${this.finalizer?'<button class="btn btn-secondary" id="annual-settings">前年調整の設定</button>':''}<button class="btn btn-ghost" id="annual-back">戻る</button></div><p>初期設定: 前年11月の締日後の金額を${this.settings.include_previous_tail?'年間集計に含む':'年間集計から除外'}</p><div class="table-wrap"><table class="data-table"><thead><tr><th>年度</th><th>版</th><th>状態</th><th>理由</th><th>操作</th></tr></thead><tbody>${data.closings.map(row=>`<tr><td>${row.fiscal_year}年11月期</td><td>第${row.revision_no}版</td><td>${status[row.status]}</td><td>${this.e(row.reason)}</td><td><button class="btn btn-secondary" data-annual="${row.annual_closing_id}">明細・確認</button></td></tr>`).join('')}</tbody></table></div>`,this.options.onBack);
      document.getElementById('annual-new')?.addEventListener('click',()=>this.editor());document.getElementById('annual-back').onclick=this.options.onBack;
      this.ctx.app.querySelectorAll('[data-annual]').forEach(button=>button.onclick=()=>this.show(Number(button.dataset.annual)));
      document.getElementById('annual-settings')?.addEventListener('click',()=>this.run(async()=>{const include=window.confirm('前年11月の締日後の金額を翌年度にも含めますか？\nOK: 含める ／ キャンセル: 含めない');const reason=window.prompt('設定変更の理由');if(!reason)return;await this.api('/settings',{include_previous_tail:include,version:this.settings.version,reason});await this.list();}));
    });},
    figures(snapshot){if(!snapshot.totals)return '';return `<div class="annual-totals">${[['通常集計',snapshot.normal],['当年11月締日後',snapshot.tail],['前年調整（控除）',snapshot.settings.include_previous_tail?{billing:0,payment:0}:snapshot.previous],['年間総額',snapshot.totals]].map(([label,v])=>`<div class="panel"><strong>${label}</strong><p>請求 ${this.money(v.billing)}</p><p>支払 ${this.money(v.payment)}</p></div>`).join('')}</div><p><strong>年間利益 ${this.money(snapshot.totals.profit)}</strong> ／ 利益率 ${snapshot.totals.profit_rate==null?'対象なし':snapshot.totals.profit_rate.toFixed(2)+'%'}</p>`;},
    detail(snapshot){return `${this.figures(snapshot)}<details><summary>未確認・確認事項 ${snapshot.warnings?.length||0}件</summary>${(snapshot.warnings||[]).map(w=>`<p>案件#${w.project_id} ${this.e(w.month||'')}: ${this.e(w.message)}</p>`).join('')||'<p>ありません</p>'}</details>${(snapshot.details||[]).map(d=>`<details class="panel"><summary>${this.e(d.project.company_name)} / ${this.e(d.project.template_name||`案件#${d.project.project_id}`)} / ${this.e(d.project.partner_name)}: 通常請求 ${this.money(d.normal.billing)}・11月追加請求 ${this.money(d.tail.billing)}</summary><p>通常支払 ${this.money(d.normal.payment)} ／ 11月追加支払 ${this.money(d.tail.payment)}</p><p>11月尾部: ${this.e(d.tail_start||'末日締めのため対象なし')} ${d.tail_start?'〜'+this.e(d.tail_end):''}</p><p>手動計上: 請求 ${this.money(d.tail_manual.billing)} / 支払 ${this.money(d.tail_manual.payment)} / ${this.e(d.tail_manual.reason||'')}</p><div class="table-wrap"><table class="data-table"><thead><tr><th>勤務日</th><th>日報</th><th>請求実績</th><th>支払実績</th></tr></thead><tbody>${d.tail_reports.map(r=>`<tr><td>${this.e(r.work_date)}</td><td>#${r.daily_report_id}</td><td>${this.money(r.override_billing_amount??r.calculated_billing_amount)}</td><td>${this.money(r.override_payment_amount??r.calculated_payment_amount)}</td></tr>`).join('')}</tbody></table></div><details><summary>通常締めの根拠</summary>${d.normal_sources.map(s=>`<p>${this.e(s.target_year_month)} / ${s.approved?'月次承認済み':'未承認実績'} / 請求 ${this.money(s.totals.billing)} / 支払 ${this.money(s.totals.payment)}</p>`).join('')}</details><details><summary>燃料・日別追加項目の根拠</summary>${d.tail_items.map(i=>`<p>${this.e(i.item_name)} / ${this.e(i.work_date||'期間内の日別燃料')} / 基準日 ${this.e(i.calculation_data?.fuel?.reference_date||'指定なし')} / ${this.e(i.reason||'')}</p>`).join('')}</details></details>`).join('')}`;},
    async show(id){await this.run(async()=>{
      const data=await this.api(`/${id}`),row=data.closing;
      const canEdit=this.office&&['draft','returned','finalized'].includes(row.status);
      const myReviews=data.reviews.filter(r=>Number(r.reviewer_user_id)===Number(this.ctx.currentUser.user_id)&&r.status==='pending');
      this.shell(`${row.fiscal_year}年11月期・第${row.revision_no}版`, `<h2>${status[row.status]}</h2><p>${this.e(row.reason)}</p><div class="btn-row">${canEdit?`<button class="btn btn-secondary" id="annual-edit">${row.status==='finalized'?'理由付き訂正版を作成':'再計算・変更'}</button>`:''}${this.office&&['draft','returned'].includes(row.status)?'<button class="btn" id="annual-submit">事務確認して営業へ申請</button>':''}${this.finalizer&&row.status==='reviewed'?'<button class="btn" id="annual-finalize">年度確定・保存帳票を作成</button>':''}<button class="btn btn-ghost" id="annual-list">年度一覧へ</button></div>${this.detail(row.snapshot_data)}
        ${(row.snapshot_data.blockers||[]).length?`<div class="error">${row.snapshot_data.blockers.map(b=>`<p>${this.e(b)}</p>`).join('')}</div>`:''}
        ${data.reconciliation?`<p>現在の通常締め・実績との照合差額: 請求 ${this.money(data.reconciliation.difference.billing)} / 支払 ${this.money(data.reconciliation.difference.payment)} ${data.reconciliation.source_changed?'（根拠の版に変更あり）':''}</p>`:''}
        <h3>担当営業の確認</h3>${data.reviews.filter(r=>r.status!=='superseded').map(r=>`<p>${myReviews.includes(r)?`<input type="checkbox" data-review-project="${r.project_id}">`:''}案件#${r.project_id} / ${this.e(r.display_name)} / ${r.assignment_source==='admin_fallback'?'管理者代行 / ':''}${status[r.status]} ${this.e(r.note||'')}</p>`).join('')||'<p>営業申請時に担当を割り当てます。</p>'}
        ${myReviews.length?'<div class="btn-row"><button class="btn" id="annual-review">選択した担当案件を確認</button><button class="btn btn-ghost" id="annual-return">選択した案件を差戻し</button></div>':''}
        <h3>年度専用保存帳票</h3><div class="btn-row">${data.documents.map(d=>`<a class="btn btn-secondary" href="/api/annual-closings/${id}/documents/${d.annual_document_id}" target="_blank" rel="noopener">${d.document_type==='invoice'?'請求':'支払'}保存帳票 PDF</a>`).join('')||'確定時に版付きで保存します。'}</div>`,()=>this.list());
      document.getElementById('annual-list').onclick=()=>this.list();document.getElementById('annual-edit')?.addEventListener('click',()=>this.editor(row));
      for(const action of ['submit','finalize'])document.getElementById(`annual-${action}`)?.addEventListener('click',event=>this.run(async()=>{event.currentTarget.disabled=true;try{await this.api(`/${id}/${action}`,{version:row.version});await this.show(id);}catch(e){event.target.disabled=false;throw e;}}));
      for(const action of ['review','return'])document.getElementById(`annual-${action}`)?.addEventListener('click',()=>this.run(async()=>{const ids=[...this.ctx.app.querySelectorAll('[data-review-project]:checked')].map(el=>Number(el.dataset.reviewProject));const reason=action==='return'?window.prompt('差戻し理由'):'';if(action==='return'&&!reason)return;await this.api(`/${id}/review`,{version:row.version,project_ids:ids,action:action==='return'?'return':'approve',reason});await this.show(id);}));
    });},
    async editor(existing=null){
      const input=existing?.input_data||{},now=new Date(),year=existing?.fiscal_year||(now.getMonth()===11?now.getFullYear()+1:now.getFullYear());
      const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${this.e(value)}" ${type==='number'?'step="1"':''}></label>`;
      this.shell(existing?.status==='finalized'?'年度訂正版の作成':'年度集計の作成・確認',`<p>初年度の前年額と、11月締日後の月額・期間一括費用は明示確認が必要です。通常の日別実績・燃料は自動集計します。</p>${existing?.status==='finalized'?'<p class="error">訂正版の下書きを保存すると旧版の入力保護を解除します。旧版とPDFは保持されます。元の日報を訂正した後、この下書きを再計算して再申請してください。</p>':''}<form id="annual-form"><div class="form-grid">${field('fiscal_year','年度（11月期の年）',year,'number')}${field('reason','作成・訂正理由',existing?.status==='finalized'?'':existing?.reason||'年度末の実績確認')}
        <label><input name="previous_confirmed" type="checkbox" ${input.previous_confirmed?'checked':''}> 初年度の前年11月尾部を確認した</label><label><input name="previous_none" type="checkbox" ${input.previous_none?'checked':''}> 初年度の前年分は該当なし</label>${field('previous_billing','初年度の前年請求計上額（円）',input.previous_billing??0,'number')}${field('previous_payment','初年度の前年支払計上額（円）',input.previous_payment??0,'number')}${field('previous_reason','前年額の根拠',input.previous_reason||'')}<label><input name="acknowledge_warnings" type="checkbox" ${input.acknowledge_warnings?'checked':''}> 下記の未確認事項を確認した</label>${field('warning_reason','未確認事項を確認した理由',input.warning_reason||'')}</div><div id="annual-manual"></div></form><div class="btn-row"><button class="btn btn-secondary" id="annual-preview">集計・差分を確認</button><button class="btn" id="annual-save" disabled>下書きを保存</button><button class="btn btn-ghost" id="annual-cancel">戻る</button></div><div id="annual-preview-result"></div>`,()=>existing?this.show(existing.annual_closing_id):this.list());
      const form=document.getElementById('annual-form');let preview,payload;
      const manualHtml=snapshot=>snapshot.details.filter(d=>d.tail_start).map(d=>{const saved=(payload?.input.tail_adjustments||input.tail_adjustments||[]).find(i=>Number(i.project_id)===Number(d.project.project_id))||{};return `<fieldset data-annual-manual="${d.project.project_id}"><legend>${this.e(d.project.company_name)} / 案件#${d.project.project_id} の11月尾部 ${this.e(d.tail_start)}〜${this.e(d.tail_end)}</legend><p>月額・月間距離超過・期間一括項目の計上額を指定してください。日別実績と燃料の日別額は含めません。該当なしは0円と理由を確認します。</p><div class="form-grid">${field('manual_billing','請求計上額（円）',saved.billing??0,'number')}${field('manual_payment','支払計上額（円）',saved.payment??0,'number')}${field('manual_reason','計上根拠・該当なしの理由',saved.reason||'')}<label><input type="checkbox" name="manual_confirmed" ${saved.confirmed?'checked':''}> この計上額を確認した</label></div></fieldset>`;}).join('');
      form.oninput=()=>{document.getElementById('annual-save').disabled=true;};
      document.getElementById('annual-preview').onclick=()=>this.run(async()=>{
        const v=Object.fromEntries(new FormData(form));const adjustments=[...form.querySelectorAll('[data-annual-manual]')].map(el=>({project_id:Number(el.dataset.annualManual),billing:Number(el.querySelector('[name=manual_billing]').value),payment:Number(el.querySelector('[name=manual_payment]').value),reason:el.querySelector('[name=manual_reason]').value,confirmed:el.querySelector('[name=manual_confirmed]').checked}));
        payload={fiscal_year:Number(v.fiscal_year),reason:v.reason,annual_closing_id:existing?.status!=='finalized'?existing?.annual_closing_id:undefined,version:existing?.version,correction_of_id:existing?.status==='finalized'?existing.annual_closing_id:undefined,input:{previous_confirmed:!!v.previous_confirmed,previous_none:!!v.previous_none,previous_billing:Number(v.previous_billing),previous_payment:Number(v.previous_payment),previous_reason:v.previous_reason,acknowledge_warnings:!!v.acknowledge_warnings,warning_reason:v.warning_reason,tail_adjustments:adjustments.length?adjustments:input.tail_adjustments||[]}};
        preview=(await this.api('/preview',{fiscal_year:payload.fiscal_year,input:payload.input})).preview;payload.source_token=preview.source_token;
        document.getElementById('annual-manual').innerHTML=manualHtml(preview);document.getElementById('annual-preview-result').innerHTML=this.detail(preview);document.getElementById('annual-error').textContent=preview.blockers.join('\n');document.getElementById('annual-save').disabled=false;
      });
      document.getElementById('annual-save').onclick=()=>this.run(async()=>{const result=await this.api('/draft',payload);await this.show(result.annual_closing_id);});
      document.getElementById('annual-cancel').onclick=()=>existing?this.show(existing.annual_closing_id):this.list();
    },
  };window.LinksAnnualClosings=ui;
})();
