(() => {
  const stageLabels = { daily:'日次金額',aggregate:'月次集約',deduction:'控除',tax:'税・丸め',finalize:'最終金額' };
  const sideLabels = { billing:'請求',payment:'支払',both:'共通' };
  const handlerLabels = { daily_price_v1:'現行の日次料金 v1',aggregate_sum_v1:'明細合計 v1',deduction_sum_v1:'控除合計 v1',tax_v1:'消費税 v1',finalize_v1:'最終金額 v1' };
  const statusLabels = { draft:'下書き',published:'公開中',retired:'廃止' };

  const LinksCalculationRules = {
    async open(ctx) { this.ctx=ctx; this.kit=window.LinksFeatureKit.createFeatureKit(ctx); await this.showList(); },
    shell(title,body,onBack) { this.ctx.app.innerHTML=this.kit.shell(title,`<section class="panel">${body}</section>`,onBack ? { onBack } : {}); this.kit.bindShell(onBack ? { onBack } : {}); },
    async showList(message='') {
      this.ctx.renderLoading(); const { res,data }=await this.ctx.api('/api/calculation-rules');
      if (!res.ok) return this.shell('計算ルール管理',`<p class="error">${this.ctx.escapeHtml(data?.message || '取得できませんでした')}</p>`);
      const rows=(data.rule_sets || []).map((row)=>`<tr><td>${this.ctx.escapeHtml(row.rule_set_name)}</td><td>${row.version_no}</td><td><span class="status-badge status-${row.status==='published'?'complete':row.status==='draft'?'working':'inactive'}">${statusLabels[row.status] || row.status}</span></td><td>${this.ctx.escapeHtml(String(row.effective_from || '-').slice(0,10))}</td><td>${row.rule_count}</td><td><button class="btn btn-ghost btn-small" data-open-rule="${row.calculation_rule_set_id}">詳細</button></td></tr>`).join('');
      this.shell('計算ルール管理',`${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}<p class="muted">公開済みの版は変更できません。既存版から下書きを作り、検証と比較を通してから公開します。</p><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>版</th><th>状態</th><th>適用開始</th><th>処理数</th><th>操作</th></tr></thead><tbody>${rows || '<tr><td colspan="6">登録がありません</td></tr>'}</tbody></table></div>`);
      document.querySelectorAll('[data-open-rule]').forEach((button)=>button.addEventListener('click',()=>this.showDetail(button.dataset.openRule)));
    },
    ruleRow(rule,index,editable) {
      const option=(values,current,labels)=>values.map((value)=>`<option value="${value}" ${value===current?'selected':''}>${labels[value] || value}</option>`).join('');
      const tax=rule.handler_code==='tax_v1'; const params=rule.parameter_json || {}; const rounding=rule.rounding_json || {};
      return `<tr data-rule-row><td><input data-field="rule_name" value="${this.ctx.escapeHtml(rule.rule_name || '')}" ${editable?'':'disabled'}><input type="hidden" data-field="rule_code" value="${this.ctx.escapeHtml(rule.rule_code || `rule_${index+1}`)}"></td><td><select data-field="stage_code" ${editable?'':'disabled'}>${option(Object.keys(stageLabels),rule.stage_code,stageLabels)}</select></td><td><select data-field="side_code" ${editable?'':'disabled'}>${option(Object.keys(sideLabels),rule.side_code,sideLabels)}</select></td><td><select data-field="handler_code" ${editable?'':'disabled'}>${option(Object.keys(handlerLabels),rule.handler_code,handlerLabels)}</select></td><td><input data-field="condition_expression" placeholder="必要な場合だけ" value="${this.ctx.escapeHtml(rule.condition_expression || '')}" ${editable?'':'disabled'}></td><td>${tax?`請求税率・端数は請求先→案件→システム設定で決定<input type="hidden" data-tax-rate value="${Number(params.rate ?? .1)*100}"><input type="hidden" data-round-mode value="${this.ctx.escapeHtml(rounding.mode || 'floor')}">`:'固定処理'}</td><td>${editable?`<button class="btn btn-danger btn-small" data-remove-rule>削除</button>`:''}<input type="hidden" data-field="sort_order" value="${rule.sort_order || (index+1)*10}"><input type="hidden" data-field="is_active" value="${rule.is_active===false?0:1}"></td></tr>`;
    },
    collectRules() { return [...document.querySelectorAll('[data-rule-row]')].map((row,index)=>{ const value=(name)=>row.querySelector(`[data-field="${name}"]`)?.value; const handler=value('handler_code'); return { rule_code:value('rule_code') || `rule_${index+1}`,rule_name:value('rule_name'),stage_code:value('stage_code'),side_code:value('side_code'),handler_code:handler,condition_expression:value('condition_expression') || null,parameter_json:handler==='tax_v1'?{ rate:Number(row.querySelector('[data-tax-rate]')?.value || 10)/100 }:{},rounding_json:handler==='tax_v1'?{ mode:row.querySelector('[data-round-mode]')?.value || 'floor',unit:1 }:{},output_code:null,sort_order:(index+1)*10,is_active:true }; }); },
    async showDetail(id,message='') {
      this.ctx.renderLoading(); const { res,data }=await this.ctx.api(`/api/calculation-rules/${id}`); if (!res.ok) return window.alert(data?.message || '取得失敗');
      this.current=data; const editable=data.rule_set.status==='draft'; const rows=(data.rules || []).map((rule,index)=>this.ruleRow(rule,index,editable)).join('');
      this.shell(`${data.rule_set.rule_set_name}（第${data.rule_set.version_no}版）`,`${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}<div class="form-grid"><div class="full"><label>名称</label><input id="rule-set-name" value="${this.ctx.escapeHtml(data.rule_set.rule_set_name)}" ${editable?'':'disabled'}></div><div><label>適用開始日</label><input id="rule-effective-from" type="date" value="${String(data.rule_set.effective_from || '').slice(0,10)}" ${editable?'':'disabled'}></div><div><label>適用終了日</label><input id="rule-effective-to" type="date" value="${String(data.rule_set.effective_to || '').slice(0,10)}" ${editable?'':'disabled'}></div></div><div class="table-wrap"><table class="data-table calculation-rule-table"><thead><tr><th>処理名</th><th>段階</th><th>対象</th><th>計算方法</th><th>適用条件</th><th>設定</th><th></th></tr></thead><tbody id="rule-rows">${rows}</tbody></table></div><div class="toolbar">${editable?'<button class="btn" id="rule-save">下書き保存</button><button class="btn btn-secondary" id="rule-validate">検証</button><button class="btn btn-secondary" id="rule-compare">現行版と比較</button><button class="btn" id="rule-publish">公開</button>':'<button class="btn" id="rule-clone">この版から下書きを作る</button><button class="btn btn-secondary" id="rule-recalc">選択して再計算</button>'}</div><div id="rule-result"></div>`,()=>this.showList());
      document.querySelectorAll('[data-remove-rule]').forEach((button)=>button.addEventListener('click',()=>button.closest('tr').remove()));
      document.getElementById('rule-save')?.addEventListener('click',()=>this.save(id)); document.getElementById('rule-validate')?.addEventListener('click',()=>this.validate(id)); document.getElementById('rule-compare')?.addEventListener('click',()=>this.compare(id)); document.getElementById('rule-publish')?.addEventListener('click',()=>this.publish(id)); document.getElementById('rule-clone')?.addEventListener('click',()=>this.clone(id)); document.getElementById('rule-recalc')?.addEventListener('click',()=>this.showCandidates(id));
    },
    payload() { return { version:Number(this.current.rule_set.version),rule_set_name:document.getElementById('rule-set-name').value.trim(),effective_from:document.getElementById('rule-effective-from').value || null,effective_to:document.getElementById('rule-effective-to').value || null,rules:this.collectRules() }; },
    async save(id) { const result=await this.ctx.api(`/api/calculation-rules/${id}`,{ method:'PUT',body:JSON.stringify(this.payload()) }); if (!result.res.ok) { window.alert(result.data?.message || '保存失敗'); return false; } await this.showDetail(id,'下書きを保存しました'); return true; },
    async validate(id) { if (!await this.save(id)) return; const result=await this.ctx.api(`/api/calculation-rules/${id}/validate`,{ method:'POST',body:'{}' }); const target=document.getElementById('rule-result'); if (!target) return; target.innerHTML=result.res.ok?'<p class="flash">検証に合格しました。</p>':`<div class="foundation-master-warning"><strong>検証エラー</strong><ul>${(result.data?.validation?.errors || [result.data?.message]).map((line)=>`<li>${this.ctx.escapeHtml(line)}</li>`).join('')}</ul></div>`; },
    async compare(id) { if (!await this.save(id)) return; const result=await this.ctx.api(`/api/calculation-rules/${id}/compare`,{ method:'POST',body:'{}' }); if (!result.res.ok) return window.alert(result.data?.message || '比較失敗'); document.getElementById('rule-result').innerHTML=`<h3>現行版との比較</h3><p class="muted">標準例での比較です。実データ全件を検証するものではありません。</p><div class="table-wrap"><table class="data-table"><thead><tr><th>例</th><th>現行</th><th>改定後</th><th>差額</th></tr></thead><tbody>${result.data.results.map((row)=>`<tr><td>${this.ctx.escapeHtml(row.name)}</td><td>${row.before_total ?? '-'}</td><td>${row.after_total}</td><td>${row.difference ?? '-'}</td></tr>`).join('')}</tbody></table></div>`; },
    async publish(id) { if (!await this.save(id)) return; if (!window.confirm('検証済みの下書きを公開しますか？ 公開後は変更できません。')) return; const result=await this.ctx.api(`/api/calculation-rules/${id}/publish`,{ method:'POST',body:'{}' }); if (!result.res.ok) return window.alert(result.data?.message || '公開失敗'); await this.showDetail(id,'計算ルールを公開しました'); },
    async clone(id) { const start=window.prompt('新しい版の適用開始日を YYYY-MM-DD で入力してください'); if (!start) return; const result=await this.ctx.api(`/api/calculation-rules/${id}/clone`,{ method:'POST',body:JSON.stringify({ effective_from:start }) }); if (!result.res.ok) return window.alert(result.data?.message || '下書き作成失敗'); await this.showDetail(result.data.calculation_rule_set_id,'下書きを作成しました'); },
    async showCandidates(id) { const result=await this.ctx.api(`/api/calculation-rules/${id}/recalculation-candidates`); if (!result.res.ok) return window.alert(result.data?.message || '候補取得失敗'); const group=(key,label,rows,idKey,text)=>`<h3>${label}</h3>${rows.length?rows.map((row)=>`<label class="check-item"><input type="checkbox" data-recalc-type="${key}" value="${row[idKey]}"><span>${this.ctx.escapeHtml(text(row))}</span></label>`).join(''):'<p class="muted">候補はありません。</p>'}`; document.getElementById('rule-result').innerHTML=`<div class="recalculation-candidates"><p class="muted">チェックした未確定の下書きだけを、この公開版で再計算します。</p>${group('daily_report_ids','日報',result.data.daily_reports,'daily_report_id',(r)=>`${r.work_date} / ${r.company_name || '-'} / ${r.partner_name || '-'}`)}${group('invoice_ids','請求',result.data.invoices,'invoice_id',(r)=>`${r.target_year_month} / ${r.company_name || '-'}`)}${group('payment_ids','支払',result.data.payments,'payment_id',(r)=>`${r.target_year_month} / ${r.partner_name || '-'}`)}<button class="btn" id="run-recalculation">選択したデータを再計算</button></div>`; document.getElementById('run-recalculation').addEventListener('click',()=>this.recalculate(id)); },
    async recalculate(id) { const payload={ daily_report_ids:[],invoice_ids:[],payment_ids:[] }; document.querySelectorAll('[data-recalc-type]:checked').forEach((input)=>payload[input.dataset.recalcType].push(Number(input.value))); if (!Object.values(payload).some((ids)=>ids.length)) return window.alert('再計算するデータを選択してください'); if (!window.confirm('選択した未確定データを再計算しますか？')) return; const result=await this.ctx.api(`/api/calculation-rules/${id}/recalculate`,{ method:'POST',body:JSON.stringify(payload) }); if (!result.res.ok) return window.alert(result.data?.message || '再計算失敗'); const value=result.data.result; await this.showDetail(id,`再計算しました（日報${value.daily_reports}件、請求${value.invoices}件、支払${value.payments}件、対象外${value.skipped.length}件）`); },
  };
  window.LinksCalculationRules=LinksCalculationRules;
})();
