(() => {
  const ui = {
    async open(ctx) { this.ctx=ctx; this.kit=window.LinksFeatureKit.createFeatureKit(ctx); this.codes=await this.kit.loadCodes(); this.ym=this.kit.currentYearMonth(); await this.list(); },
    money: (v) => Number(v || 0).toLocaleString('ja-JP'),
    status: (v) => ({draft:'下書き',sales_reviewed:'営業確認済み',finalized:'最終確定',cancelled:'取消済み'}[v] || v || '下書き'),
    async list(message='') {
      this.ctx.renderLoading(); const [targets, rows]=await Promise.all([this.ctx.api(`/api/invoices/targets?target_year_month=${this.ym}`),this.ctx.api(`/api/invoices?target_year_month=${this.ym}`)]);
      if(!targets.res.ok) return this.error(targets.data?.message);
      this.targets=targets.data.targets||[];
      const todo=this.targets.map((x,i)=>`<tr><td>${this.ctx.escapeHtml(x.billing_print_name||x.company_name)}</td><td>${x.report_count}</td><td>${this.money(x.subtotal_amount)}円</td><td><button class="btn btn-small" data-draft="${i}">下書き作成</button></td></tr>`).join('');
      const issued=(rows.data?.invoices||[]).map(x=>`<tr><td>#${x.invoice_id}</td><td>${this.ctx.escapeHtml(x.company_name||x.company_id)}</td><td>${this.money(x.total_amount)}円</td><td>${this.status(x.settlement_status)}</td><td><button class="btn btn-ghost btn-small" data-open="${x.invoice_id}">開く</button></td></tr>`).join('');
      this.ctx.app.innerHTML=this.kit.shell('請求',`<section class="panel">${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}<div class="toolbar"><input id="ym" type="month" value="${this.ym}"><button id="load" class="btn">表示</button></div><h3 class="section-title">月次承認済み日報から作成</h3><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>請求先</th><th>日報</th><th>見込税抜</th><th>操作</th></tr></thead><tbody>${todo||'<tr><td colspan="4">対象なし</td></tr>'}</tbody></table></div><h3 class="section-title">請求一覧</h3><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>No</th><th>企業</th><th>税込</th><th>状態</th><th>操作</th></tr></thead><tbody>${issued||'<tr><td colspan="5">なし</td></tr>'}</tbody></table></div></section>`);this.kit.bindShell();
      document.getElementById('load').onclick=()=>{this.ym=document.getElementById('ym').value;this.list();};document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>this.draft(this.targets[Number(b.dataset.draft)]));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{this.kit.pushNav(()=>this.list());this.detail(Number(b.dataset.open));});
    },
    async draft(t) { const amount=window.prompt('手動調整額（不要なら0）','0');if(amount===null)return;const reason=Number(amount)<0?window.prompt('負額調整の理由',''):'';if(Number(amount)<0&&!reason)return window.alert('負額調整には理由が必要です');const r=await this.ctx.api('/api/settlements/invoice/drafts',{method:'POST',body:JSON.stringify({target_year_month:this.ym,company_id:t.company_id,daily_report_ids:t.report_ids,closing_date:t.closing_date||'end',adjustments:Number(amount)?[{item_name:'手動調整',amount:Number(amount),reason}]:[]})});if(!r.res.ok)return window.alert(r.data?.message||'作成失敗');this.kit.pushNav(()=>this.list());this.detail(r.data.settlement_id);},
    async detail(id) { this.ctx.renderLoading();const r=await this.ctx.api(`/api/settlements/invoice/${id}`);if(!r.res.ok)return this.error(r.data?.message,()=>this.list());const {settlement:s,workflow:w,lines=[],documents=[]}=r.data;const lineRows=lines.map(x=>`<tr><td>${this.ctx.escapeHtml(x.item_name)}</td><td>${this.ctx.escapeHtml(x.line_type)}</td><td>${this.money(x.amount)}円</td><td>${this.ctx.escapeHtml(x.tax_category)}</td></tr>`).join('');const docs=documents.map(x=>`<li>${this.ctx.escapeHtml(x.document_number)} <a href="/api/settlements/documents/${x.settlement_document_id}/download">PDF</a></li>`).join('');
      this.ctx.app.innerHTML=this.kit.shell(`請求 #${id}`,`<section class="panel"><div class="preview-sheet"><h3>請求確定内容</h3><p>対象月: ${s.target_year_month} / 状態: <strong>${this.status(w?.status)}</strong></p><p>税抜 ${this.money(s.subtotal_amount)}円 + 税 ${this.money(s.tax_amount)}円 = <strong>${this.money(s.total_amount)}円</strong></p></div><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>項目</th><th>種別</th><th>金額</th><th>税区分</th></tr></thead><tbody>${lineRows}</tbody></table></div><h3 class="section-title">PDF帳票</h3><ul>${docs||'<li>最終確定後に発行します</li>'}</ul><div class="btn-row">${w?.status==='draft'?'<button id="review" class="btn">営業確認</button>':''}${w?.status==='sales_reviewed'?'<select id="cycle"></select><button id="finalize" class="btn">最終確定・PDF発行</button>':''}${w?.status==='finalized'?'<button id="cancel" class="btn btn-ghost">未実行取消</button><button id="correct" class="btn btn-ghost">実行済み訂正</button>':''}<button id="back" class="btn btn-ghost">一覧へ</button></div></section>`,{onBack:()=>this.list()});this.kit.bindShell({onBack:()=>this.list()});document.getElementById('back').onclick=()=>this.list();document.getElementById('review')?.addEventListener('click',()=>this.action(`/api/settlements/invoice/${id}/sales-review`,{},()=>this.detail(id)));document.getElementById('cancel')?.addEventListener('click',()=>{const reason=window.prompt('取消理由','');if(reason)this.action(`/api/settlements/invoice/${id}/cancel`,{reason},()=>this.detail(id));});document.getElementById('correct')?.addEventListener('click',()=>this.correction(id));if(w?.status==='sales_reviewed')this.cycles(id); },
    async correction(id){const reason=window.prompt('訂正理由','');if(!reason)return;const amount=window.prompt('訂正差額（減額はマイナス）','0');if(amount===null||!Number.isFinite(Number(amount)))return window.alert('訂正差額を数値で入力してください');const body={reason,adjustments:Number(amount)?[{item_name:'訂正調整',amount:Number(amount),reason}]:[]};const r=await this.ctx.api(`/api/settlements/invoice/${id}/corrections`,{method:'POST',body:JSON.stringify(body)});if(!r.res.ok)return window.alert(r.data?.message||'訂正下書きの作成に失敗しました');this.detail(r.data.settlement_id);},
    async cycles(id){const r=await this.ctx.api(`/api/cash-management/cycles?target_year_month=${this.ym}`);const e=document.getElementById('cycle');if(!e)return;e.innerHTML=(r.data?.cycles||[]).map(x=>`<option value="${x.cash_cycle_id}">${x.cycle_code==='end'?'末日':Number(x.cycle_code)}日回</option>`).join('');document.getElementById('finalize').onclick=()=>this.action(`/api/settlements/invoice/${id}/finalize`,{cash_cycle_id:Number(e.value)},()=>this.detail(id));},
    async action(path,body,next){const r=await this.ctx.api(path,{method:'POST',body:JSON.stringify(body)});if(!r.res.ok)return window.alert(r.data?.message||'処理失敗');next();},
    error(message,onBack){this.ctx.app.innerHTML=this.kit.shell('請求',`<section class="panel"><p class="error">${this.ctx.escapeHtml(message||'取得失敗')}</p></section>`,{onBack});this.kit.bindShell({onBack});},
  }; window.LinksInvoices=ui;
})();
