(() => {
  const ui = {
    kind:'invoice',
    async open(ctx) { this.ctx=ctx;this.kit=window.LinksFeatureKit.createFeatureKit(ctx);this.ym=this.kit.currentYearMonth();this.filters={q:'',closing:'',status:''};await this.list(); },
    money(v){return this.kit.money(v);},
    status(v){return ({available:'請求可能',draft:'請求書作成中',sales_reviewed:'営業確認済み',finalized:'最終確定',cancelled:'取消済み',awaiting_approval:'日報承認待ち',not_available:'対象なし',no_reports:'日報未登録'}[v]||v||'日報未登録');},
    tax(v){return ({taxable:'課税',non_taxable:'非課税',tax_exempt:'免税'}[v]||v);},
    async list(message=''){
      this.ctx.renderLoading();const [targets,rows]=await Promise.all([this.ctx.api(`/api/invoices/targets?target_year_month=${encodeURIComponent(this.ym)}`),this.ctx.api(`/api/invoices?target_year_month=${encodeURIComponent(this.ym)}`)]);if(!targets.res.ok)return this.error(targets.data?.message);
      this.targets=targets.data.targets||[];const visible=this.targets.filter(x=>{const text=`${x.project_id} ${x.project_name||''} ${x.company_name||''}`.toLowerCase();return(!this.filters.q||text.includes(this.filters.q.toLowerCase()))&&(!this.filters.closing||String(x.closing_date||'')===this.filters.closing);});
      const todo=visible.map(x=>{const available=x.target_status==='available'&&!x.tax_error;const state=x.tax_error?`<span class="error">${this.ctx.escapeHtml(x.tax_error)}</span>`:x.settlement_id?`<button class="btn btn-ghost btn-small" data-open-target="${x.settlement_id}">${this.status(x.target_status)}</button>`:available?`<button class="btn btn-small" data-single="${x.project_id}">請求可能</button>`:`<span class="status-badge">${this.status(x.target_status)}</span>`;return `<tr><td><input type="checkbox" data-project-select="${x.project_id}" data-key="${this.ctx.escapeHtml(`${x.company_id}:${x.billing_summary_no||`company-${x.company_id}`}:${x.closing_date}`)}" ${available?'':'disabled'}></td><td>#${x.project_id}</td><td>${this.ctx.escapeHtml(x.company_name||'-')}</td><td>${this.ctx.escapeHtml(x.project_name||'-')}</td><td>${x.closing_date==='end'?'末日':`${this.ctx.escapeHtml(x.closing_date||'-')}日`}</td><td>${this.ym}</td><td class="num">${this.money(x.subtotal_amount)}</td><td>${state}</td></tr>`;}).join('');
      const issued=(rows.data?.invoices||[]).filter(x=>!this.filters.status||x.settlement_status===this.filters.status).map(x=>`<tr><td>#${x.invoice_id}</td><td>${this.ctx.escapeHtml(x.billing_print_name||x.company_name||x.company_id)}</td><td>${x.closing_date==='end'?'末日':`${x.closing_date}日`}</td><td class="num">${this.money(x.total_amount)}</td><td><span class="status-badge status-${x.settlement_status}">${this.status(x.settlement_status)}</span></td><td><button class="btn btn-ghost btn-small" data-open="${x.invoice_id}">開く</button></td></tr>`).join('');
      this.ctx.app.innerHTML=this.kit.shell('請求管理',`<section class="panel">${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}${this.kit.monthNavigatorHtml(this.ym,'invoice-month')}<div class="settlement-filters"><input id="invoice-q" placeholder="案件・会社を検索" value="${this.ctx.escapeHtml(this.filters.q)}"><button id="invoice-filter" class="btn btn-secondary">絞り込み</button></div><div class="section-title-row"><h3>請求対象案件</h3><button id="create-selected" class="btn">選択案件から請求書を作成</button></div><p class="muted">案件は状態にかかわらず表示します。1案件は「請求可能」、複数案件はチェックして作成します。締日は案件設定を自動適用します。</p><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>選択</th><th>案件No</th><th>会社</th><th>案件名</th><th>締日</th><th>対象月</th><th>請求予定額</th><th>状態</th></tr></thead><tbody>${todo||'<tr><td colspan="8">案件がありません</td></tr>'}</tbody></table></div><div class="section-title-row"><h3>作成済み請求書</h3><select id="invoice-status"><option value="">全状態</option>${['draft','sales_reviewed','finalized','cancelled'].map(v=>`<option value="${v}" ${this.filters.status===v?'selected':''}>${this.status(v)}</option>`).join('')}</select></div><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>No</th><th>請求先</th><th>締日</th><th>請求額</th><th>状態</th><th>操作</th></tr></thead><tbody>${issued||'<tr><td colspan="6">作成済み請求書はありません</td></tr>'}</tbody></table></div></section>`,{wide:true});
      this.kit.bindShell();this.kit.bindMonthNavigator('invoice-month',()=>this.ym,v=>{this.ym=v;},()=>this.list());document.getElementById('invoice-filter').onclick=()=>{this.filters.q=document.getElementById('invoice-q').value.trim();this.list();};document.getElementById('invoice-status').onchange=e=>{this.filters.status=e.target.value;this.list();};document.getElementById('create-selected').onclick=()=>this.createSelected();document.querySelectorAll('[data-open],[data-open-target]').forEach(b=>b.onclick=()=>this.detail(Number(b.dataset.open||b.dataset.openTarget)));document.querySelectorAll('[data-single]').forEach(b=>b.onclick=()=>this.createProjects([Number(b.dataset.single)]));
    },
    async createSelected(){const checked=[...document.querySelectorAll('[data-project-select]:checked')];if(!checked.length)return window.alert('請求する案件を選択してください');if(new Set(checked.map(x=>x.dataset.key)).size!==1)return window.alert('請求先・請求取纏番号・締日が同じ案件だけをまとめられます');return this.createProjects(checked.map(x=>Number(x.dataset.projectSelect)));},
    async createProjects(projectIds){const ids=new Set(projectIds),selected=this.targets.filter(x=>ids.has(Number(x.project_id)));if(!selected.length||selected.some(x=>x.target_status!=='available'||x.tax_error))return window.alert('請求可能な案件を選択してください');const first=selected[0],reportIds=[...new Set(selected.flatMap(x=>x.report_ids||[]))];const r=await this.ctx.api('/api/settlements/invoice/drafts',{method:'POST',body:JSON.stringify({target_year_month:this.ym,company_id:first.company_id,billing_id:first.billing_id,billing_summary_no:first.billing_summary_no,billing_print_name:first.billing_print_name,daily_report_ids:reportIds})});if(!r.res.ok)return window.alert(r.data?.message||'下書き作成に失敗しました');this.detail(r.data.settlement_id);},
    lineRows(lines,editable){if(editable&&!this._lineCalcScheduled){this._lineCalcScheduled=true;queueMicrotask(()=>{this._lineCalcScheduled=false;this.bindLineCalculations();});}return lines.map((x,i)=>`<tr data-line-row="${x.settlement_line_id}"><td>${i+1}</td><td><input data-field="item_name" value="${this.ctx.escapeHtml(x.item_name)}" ${editable?'':'disabled'}></td><td><span class="money-input-wrap"><span>￥</span><input data-field="unit_price" type="number" step="0.01" value="${Number(x.unit_price)}" ${editable?'':'disabled'}></span></td><td><input data-field="quantity" type="number" step="0.0001" value="${Number(x.quantity)}" ${editable?'':'disabled'}></td><td><span class="money-input-wrap"><span>￥</span><input data-field="amount" type="number" step="0.01" value="${Number(x.amount)}" ${editable?'':'disabled'}></span></td><td><select data-field="tax_category" ${editable?'':'disabled'}>${['taxable','non_taxable','tax_exempt'].map(v=>`<option value="${v}" ${x.tax_category===v?'selected':''}>${this.tax(v)}</option>`).join('')}</select></td>${editable?`<td><input data-field="reason" placeholder="金額変更時のみ理由"><input data-field="version" type="hidden" value="${x.version}"><button class="btn btn-small" data-save-line="${x.settlement_line_id}">保存</button><button class="btn btn-ghost btn-small" data-up="${x.settlement_line_id}">↑</button><button class="btn btn-ghost btn-small" data-down="${x.settlement_line_id}">↓</button><button class="btn btn-danger btn-small" data-delete-line="${x.settlement_line_id}">取消</button></td>`:''}</tr>`).join('');},
    async detail(id){
      this.ctx.renderLoading();
      const r=await this.ctx.api(`/api/settlements/invoice/${id}`);
      if(!r.res.ok)return this.error(r.data?.message,()=>this.list());
      const {settlement:s,workflow:w,lines=[],documents=[],audit_logs=[]}=r.data,editable=w?.status==='draft';
      this.currentLines=lines;
      const docs=documents.map(x=>`<li>${this.ctx.escapeHtml(x.document_number)}（${x.status==='issued'?'発行済み':'取消済み'}）${x.status==='issued'?` <a href="/api/settlements/documents/${x.settlement_document_id}/download">PDF</a>`:''}</li>`).join('');
      const history=[...(w?.cancellation_reason?[{acted_at:w.cancelled_at,action_code:'取消',reason:w.cancellation_reason}]:[]),...audit_logs].slice(0,20).map(x=>`<tr><td>${this.ctx.escapeHtml(x.acted_at||'')}</td><td>${this.ctx.escapeHtml(x.action_code||'')}</td><td>${this.ctx.escapeHtml(x.reason||'摘要のみ変更')}</td></tr>`).join('');
      const actions=`${w?.status==='draft'?'<button id="review" class="btn">営業確認</button>':''}${w?.status==='sales_reviewed'?'<select id="cycle"></select><button id="finalize" class="btn">最終確定・PDF発行</button>':''}${['draft','sales_reviewed','finalized'].includes(w?.status)?'<button id="cancel" class="btn btn-ghost">取消</button>':''}${w?.status==='finalized'?'<button id="correct" class="btn btn-ghost">実行済み訂正</button>':''}<button id="back" class="btn btn-ghost">一覧へ</button>`;
      this.ctx.app.innerHTML=this.kit.shell(`請求書 #${id}`,`<section class="panel settlement-editor"><div class="document-preview"><div class="document-preview-head"><strong>${this.ctx.escapeHtml(s.billing_print_name||`企業 #${s.company_id}`)} 御中</strong><div><h2>${s.target_year_month}度ご請求書</h2><p>状態：${this.status(w?.status)}</p></div></div><div class="document-total"><span>ご請求額</span><strong>${this.money(s.total_amount)}</strong><span>内消費税 ${this.money(s.tax_amount)}</span></div><h3>請求明細</h3><div class="table-wrap"><table class="document-lines"><thead><tr><th>No.</th><th>摘要</th><th>単価</th><th>個数</th><th>金額</th><th>税区分</th>${editable?'<th>編集</th>':''}</tr></thead><tbody>${this.lineRows(lines,editable)||'<tr><td colspan="7">明細がありません</td></tr>'}</tbody><tfoot><tr><th colspan="4">小計</th><td>${this.money(s.subtotal_amount)}</td><td colspan="2"></td></tr><tr><th colspan="4">消費税</th><td>${this.money(s.tax_amount)}</td><td colspan="2"></td></tr><tr><th colspan="4">合計</th><td>${this.money(s.total_amount)}</td><td colspan="2"></td></tr></tfoot></table></div></div>${editable?'<div class="settlement-edit-actions"><button id="add-line" class="btn">＋ 金額明細を追加</button><button id="source-diff" class="btn btn-secondary">日報から再反映</button></div>':''}<h3>PDF帳票</h3><p><a class="btn btn-secondary" target="_blank" href="/api/settlements/invoice/${id}/preview">見本PDFイメージを確認</a> <span class="muted">「見本・未発行」の透かし付きです。</span></p><ul>${docs||'<li>正式PDFは最終確定後に発行します</li>'}</ul><details><summary>編集・取消履歴</summary><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>日時</th><th>操作</th><th>理由</th></tr></thead><tbody>${history||'<tr><td colspan="3">履歴はありません</td></tr>'}</tbody></table></div></details><div class="btn-row">${actions}</div></section>`,{wide:true,onBack:()=>this.list()});
      this.kit.bindShell({onBack:()=>this.list()});document.getElementById('back').onclick=()=>this.list();document.querySelectorAll('[data-save-line]').forEach(b=>b.onclick=()=>this.saveLine(id,b));document.querySelectorAll('[data-delete-line]').forEach(b=>b.onclick=()=>this.deleteLine(id,b));document.querySelectorAll('[data-up],[data-down]').forEach(b=>b.onclick=()=>this.moveLine(id,Number(b.dataset.up||b.dataset.down),Boolean(b.dataset.up)));document.getElementById('add-line')?.addEventListener('click',()=>this.addLine(id));document.getElementById('source-diff')?.addEventListener('click',()=>this.showDiff(id));document.getElementById('review')?.addEventListener('click',()=>this.action(`/api/settlements/invoice/${id}/sales-review`,{},()=>this.detail(id)));document.getElementById('cancel')?.addEventListener('click',()=>{const reason=window.prompt('取消理由','');if(reason)this.action(`/api/settlements/invoice/${id}/cancel`,{reason},()=>this.list('取消しました'));});document.getElementById('correct')?.addEventListener('click',()=>this.correction(id));if(w?.status==='sales_reviewed')this.cycles(id);
    },
    bindLineCalculations(){document.querySelectorAll('[data-line-row]').forEach(row=>{const unit=row.querySelector('[data-field="unit_price"]'),quantity=row.querySelector('[data-field="quantity"]'),amount=row.querySelector('[data-field="amount"]');if(!unit||!quantity||!amount||unit.disabled)return;const calculate=()=>{if(amount.dataset.overridden==='1')return;amount.value=String(Math.round(Number(unit.value||0)*Number(quantity.value||0)*100)/100);};unit.addEventListener('input',calculate);quantity.addEventListener('input',calculate);amount.addEventListener('input',()=>{amount.dataset.overridden='1';});});},
    rowBody(button){const row=button.closest('[data-line-row]'),v=n=>row.querySelector(`[data-field="${n}"]`)?.value;return{item_name:v('item_name'),unit_price:Number(v('unit_price')),quantity:Number(v('quantity')),amount:Number(v('amount')),tax_category:v('tax_category'),reason:v('reason'),version:Number(v('version'))};},
    saveLine(id,b){const body=this.rowBody(b),before=this.currentLines.find(x=>Number(x.settlement_line_id)===Number(b.dataset.saveLine));if(before&&Number(before.amount)!==Number(body.amount)&&!body.reason)return window.alert('金額を変更する場合は変更理由を入力してください');return this.action(`/api/settlements/${this.kind}/${id}/lines/${b.dataset.saveLine}`,body,()=>this.detail(id),'PUT');},
    deleteLine(id,b){const reason=window.prompt('明細の取消理由','');if(reason)return this.action(`/api/settlements/${this.kind}/${id}/lines/${b.dataset.deleteLine}`,{reason},()=>this.detail(id),'DELETE');},
    addLine(id){const item_name=window.prompt('摘要','調整');if(!item_name)return;const unit_price=Number(window.prompt('単価','0')),quantity=Number(window.prompt('数量','1')),raw=window.prompt('金額（空欄は単価×数量）',''),reason=window.prompt('追加理由','');if(reason)return this.action(`/api/settlements/${this.kind}/${id}/lines`,{item_name,unit_price,quantity,amount:raw===''?null:Number(raw),tax_category:'taxable',reason},()=>this.detail(id));},
    moveLine(id,lineId,up){const ids=this.currentLines.map(x=>Number(x.settlement_line_id)),index=ids.indexOf(lineId),next=index+(up?-1:1);if(index<0||next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];return this.action(`/api/settlements/${this.kind}/${id}/lines/reorder`,{line_ids:ids,reason:'帳票の表示順を変更'},()=>this.detail(id));},
    async showDiff(id){const r=await this.ctx.api(`/api/settlements/${this.kind}/${id}/source-diff`);if(!r.res.ok)return window.alert(r.data?.message||'差分取得に失敗しました');const changes=r.data.changes||[];document.body.insertAdjacentHTML('beforeend',this.kit.modalHtml('日報との差分',changes.length?`<form id="diff-form">${changes.map((x,i)=>`<label class="diff-row"><input type="checkbox" name="change" value="${i}" ${x.protected?'':'checked'}><span>${({add:'追加',update:'変更',remove:'削除'}[x.action])}</span><strong>${this.ctx.escapeHtml(x.next?.item_name||x.current?.item_name||'')}</strong><span>${this.money(x.current?.amount||0)} → ${this.money(x.next?.amount||0)}</span>${x.protected?'<em>手動編集済み（明示選択時のみ置換）</em>':''}</label>`).join('')}<label>反映理由<input name="reason" required value="日報の最新承認内容を反映"></label></form>`:'<p>差分はありません。</p>',changes.length?'<button id="apply-diff" class="btn">選択した差分を反映</button>':''));const close=this.kit.bindModal();document.getElementById('apply-diff')?.addEventListener('click',async()=>{const form=document.getElementById('diff-form'),selected=[...form.querySelectorAll('[name="change"]:checked')].map(b=>changes[Number(b.value)]);const out=await this.ctx.api(`/api/settlements/${this.kind}/${id}/source-diff/apply`,{method:'POST',body:JSON.stringify({change_keys:selected.map(x=>x.change_key),replace_line_ids:selected.filter(x=>x.protected&&x.current).map(x=>x.current.settlement_line_id),reason:new FormData(form).get('reason')})});if(!out.res.ok)return window.alert(out.data?.message||'反映に失敗しました');close();this.detail(id);});},
    async correction(id){const reason=window.prompt('訂正理由','');if(!reason)return;const r=await this.ctx.api(`/api/settlements/${this.kind}/${id}/corrections`,{method:'POST',body:JSON.stringify({reason})});if(!r.res.ok)return window.alert(r.data?.message||'訂正下書き作成に失敗しました');this.detail(r.data.settlement_id);},
    async cycles(id){const r=await this.ctx.api(`/api/cash-management/cycles?target_year_month=${this.ym}`),e=document.getElementById('cycle');if(!e)return;e.innerHTML=(r.data?.cycles||[]).map(x=>`<option value="${x.cash_cycle_id}">${x.cycle_code==='end'?'末日':Number(x.cycle_code)}日回</option>`).join('');document.getElementById('finalize').onclick=()=>this.action(`/api/settlements/invoice/${id}/finalize`,{cash_cycle_id:Number(e.value)},()=>this.detail(id));},
    async action(path,body,next,method='POST'){const r=await this.ctx.api(path,{method,body:JSON.stringify(body)});if(!r.res.ok)return window.alert(r.data?.message||'処理に失敗しました');next?.();},
    error(message,onBack){this.ctx.app.innerHTML=this.kit.shell('請求管理',`<section class="panel"><p class="error">${this.ctx.escapeHtml(message||'取得に失敗しました')}</p></section>`,{onBack});this.kit.bindShell({onBack});},
  };window.LinksInvoices=ui;
})();
