(() => {
  window.LinksMasterDataPreparation = {
    async open(ctx) { this.ctx = ctx; this.preview = null; this.prepared = null; this.message = ''; this.render(); },
    async request(path, options = {}) { const { res, data } = await this.ctx.api(path, options); if (!res.ok || !data?.ok) throw new Error(data?.message || '処理に失敗しました'); return data; },
    async action(fn) { if (this.busy) return; this.busy = true; this.message = '処理中です…'; this.render(); try { await fn(); } catch (e) { this.message = e.message; } finally { this.busy = false; this.render(); } },
    download(url) { const a = document.createElement('a'); a.href = url; a.click(); },
    render() {
      const e = this.ctx.escapeHtml;
      const summary = this.prepared ? `<div class="master-import-counts">${Object.entries(this.prepared.summary).map(([k,v]) => `<span><b>${e(k)}</b>${e(v)}件</span>`).join('')}</div><p>要確認 ${e(this.prepared.warning_count)}件</p><button class="btn" id="md-download" ${this.prepared.download_token ? '' : 'disabled'}>編集用Excelをダウンロード</button>` : '';
      const preview = this.preview ? `<div class="master-import-counts">${[['new','新規'],['update','更新'],['unchanged','変更なし'],['error','エラー'],['dependency_error','依存先エラー'],['conflict','競合']].map(([k,l]) => `<span><b>${l}</b>${e(this.preview.counts[k] || 0)}件</span>`).join('')}</div><div class="btn-row"><button class="btn" id="md-commit" ${(this.preview.counts.new + this.preview.counts.update + this.preview.counts.unchanged) ? '' : 'disabled'}>正常行を登録</button>${this.preview.error_download_token ? '<button class="btn btn-secondary" id="md-errors">エラーExcelをダウンロード</button>' : ''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>シート</th><th>行</th><th>取込キー</th><th>判定</th><th>内容</th></tr></thead><tbody>${this.preview.rows.filter(r => r.status !== 'unchanged').slice(0,500).map(r => `<tr><td>${e(r.sheet)}</td><td>${e(r.row)}</td><td>${e(r.import_key)}</td><td>${e(r.status)}</td><td>${e((r.messages || []).join(' / '))}</td></tr>`).join('')}</tbody></table></div>` : '';
      this.ctx.app.innerHTML = `<div class="app-shell">${this.ctx.sidebarHtml('master_data_preparation')}<div class="app-frame">${this.ctx.headerHtml('マスターデータ取込')}<main class="app-main"><p role="status" class="muted">${e(this.message)}</p><section class="panel"><h2>1. 原本Excelを編集用に変換</h2><p>匿名化済み原本を選択してください。原本は処理直後に削除され、DBやログへ保存されません。</p><input id="md-source" type="file" accept=".xlsx"><button class="btn" id="md-convert" ${this.busy ? 'disabled' : ''}>変換する</button>${summary}</section><section class="panel"><h2>2. 完成Excelを検証・登録</h2><p>不足項目を記入したExcelを選択します。登録前に各行の判定を確認できます。</p><input id="md-completed" type="file" accept=".xlsx"><button class="btn" id="md-preview" ${this.busy ? 'disabled' : ''}>検証する</button>${preview}</section></main></div></div>`;
      this.ctx.bindChrome(); this.bind();
    },
    bind() {
      document.getElementById('md-convert')?.addEventListener('click', () => this.action(async () => { const file = document.getElementById('md-source').files[0]; if (!file) throw new Error('原本Excelを選択してください'); const form = new FormData(); form.append('file', file); this.prepared = await this.request('/api/master-data-preparations', { method: 'POST', body: form }); this.message = '変換が完了しました。30分以内に一度だけダウンロードしてください。'; }));
      document.getElementById('md-download')?.addEventListener('click', () => { this.download(`/api/master-data-preparations/${encodeURIComponent(this.prepared.download_token)}.xlsx`); this.prepared.download_token = null; this.message = '編集用Excelをダウンロードしました。'; this.render(); });
      document.getElementById('md-preview')?.addEventListener('click', () => this.action(async () => { const file = document.getElementById('md-completed').files[0]; if (!file) throw new Error('完成Excelを選択してください'); const form = new FormData(); form.append('file', file); this.preview = await this.request('/api/master-data-imports/preview', { method: 'POST', body: form }); this.message = '検証が完了しました。内容を確認して登録してください。'; }));
      document.getElementById('md-errors')?.addEventListener('click', () => { this.download(`/api/master-data-imports/${encodeURIComponent(this.preview.error_download_token)}/errors.xlsx`); this.preview.error_download_token = null; this.render(); });
      document.getElementById('md-commit')?.addEventListener('click', () => this.action(async () => { if (!window.confirm('プレビューで正常と判定された行を登録します。よろしいですか？')) return; const result = await this.request(`/api/master-data-imports/${encodeURIComponent(this.preview.preview_token)}/commit`, { method: 'POST', body: '{}' }); this.message = `登録しました（新規 ${result.created}、更新 ${result.updated}、変更なし ${result.unchanged}、除外 ${result.skipped}）。`; this.preview = null; }));
    },
  };
})();
