(() => {
  window.LinksMasterDataPreparation = {
    async open(ctx, options = {}) { this.ctx = ctx; this.mode = options.featureKey || 'master_data_preparation'; this.preview = null; this.prepared = null; this.restore = null; this.exported = null; this.message = ''; this.render(); },
    async request(path, options = {}) { const { res, data } = await this.ctx.api(path, options); if (!res.ok || !data?.ok) throw new Error(data?.message || '処理に失敗しました'); return data; },
    async action(fn) { if (this.busy) return; this.busy = true; this.message = '処理中です…'; this.ctx.app.querySelectorAll('main button').forEach((button)=>{button.disabled=true;}); try { await fn(); } catch (e) { this.message = e.message; } finally { this.busy = false; this.render(); } },
    download(url) { const a = document.createElement('a'); a.href = url; a.click(); },
    render() {
      const e = this.ctx.escapeHtml;
      const title = { master_data_preparation:'マスターデータ取込', db_import:'DB取込', db_export:'DB出力', master_data_export:'マスターデータ出力' }[this.mode] || 'マスターデータ取込';
      const summary = this.prepared ? `<div class="master-import-counts">${Object.entries(this.prepared.summary).map(([k,v]) => `<span><b>${e(k)}</b>${e(v)}件</span>`).join('')}</div><p>要確認 ${e(this.prepared.warning_count)}件</p><button class="btn" id="md-download" ${this.prepared.download_token ? '' : 'disabled'}>編集用Excelをダウンロード</button>` : '';
      const preview = this.preview ? `<div class="master-import-counts">${[['new','新規'],['update','更新'],['unchanged','変更なし'],['error','エラー'],['dependency_error','依存先エラー'],['conflict','競合']].map(([k,l]) => `<span><b>${l}</b>${e(this.preview.counts[k] || 0)}件</span>`).join('')}</div><div class="btn-row"><button class="btn" id="md-commit" ${(this.preview.counts.new + this.preview.counts.update + this.preview.counts.unchanged) ? '' : 'disabled'}>正常行を登録</button>${this.preview.error_download_token ? '<button class="btn btn-secondary" id="md-errors">エラーExcelをダウンロード</button>' : ''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>シート</th><th>行</th><th>取込キー</th><th>判定</th><th>内容</th></tr></thead><tbody>${this.preview.rows.filter(r => r.status !== 'unchanged').slice(0,500).map(r => `<tr><td>${e(r.sheet)}</td><td>${e(r.row)}</td><td>${e(r.import_key)}</td><td>${e(r.status)}</td><td>${e((r.messages || []).join(' / '))}</td></tr>`).join('')}</tbody></table></div>` : '';
      const restoreRows = this.restore ? `<p>差分 ${e(this.restore.counts.update || 0)}件、新規 ${e(this.restore.counts.new || 0)}件、競合 ${e(this.restore.counts.conflict || 0)}件</p><div class="table-wrap"><table class="data-table"><thead><tr><th>復旧</th><th>シート</th><th>キー</th><th>判定</th><th>差分（現在値 → 初期値）</th></tr></thead><tbody>${this.restore.rows.filter(r=>r.status!=='unchanged').map(r=>`<tr><td>${['new','update'].includes(r.status)?`<input type="checkbox" data-restore-key="${e(`${r.sheet}:${r.key}`)}" aria-label="${e(r.sheet)} ${e(r.key)} を復旧">`:''}</td><td>${e(r.sheet)}</td><td>${e(r.key)}</td><td>${e(r.status)}</td><td>${e(r.changed_fields.map(f=>`${f}: ${r.current[f]??'（なし）'} → ${r.initial[f]??'（空欄）'}`).join(' / ')||r.reason)}</td></tr>`).join('')}</tbody></table></div><button class="btn" id="md-restore-commit">選択した項目を復旧</button>` : '';
      const sections = this.mode === 'master_data_preparation' ? `<section class="panel"><h2>原本Excelを編集用に変換</h2><p>原本は処理直後に削除され、DBやログへ保存されません。</p><input id="md-source" type="file" accept=".xlsx"><button class="btn" id="md-convert" ${this.busy ? 'disabled' : ''}>変換する</button>${summary}</section><section class="panel"><h2>基盤マスター初期値を選択復旧</h2><p>「マスターデータ出力」で取得した、このシステム版の初期値Excelを選んで差分を確認します。選択した行だけ復旧します。</p><input id="md-restore-source" type="file" accept=".xlsx"><button class="btn btn-secondary" id="md-restore-preview">初期値との差分を確認</button>${restoreRows}</section>` : this.mode === 'db_import' ? `<section class="panel"><h2>完成Excelを検証・登録</h2><p>マスターデータ取込で変換したExcel、またはDB出力で取得したExcelを選択します。変更前に各行の判定を確認できます。</p><input id="md-completed" type="file" accept=".xlsx"><button class="btn" id="md-preview" ${this.busy ? 'disabled' : ''}>検証する</button>${preview}</section>` : `<section class="panel"><h2>${e(title)}</h2><p>${this.mode === 'db_export' ? '現行DBの企業・パートナー・案件・料金を編集用Excelに出力します。編集後はDB取込で検証してください。' : 'システムに同梱された基盤マスターの初期値Excelを取得します。現行DBの値はDB出力を利用してください。'}</p><button class="btn" id="md-export" ${this.busy ? 'disabled' : ''}>Excelを作成</button>${this.exported ? `<p>${this.exported.summary ? Object.entries(this.exported.summary).map(([k,v])=>`${e(k)} ${e(v)}件`).join('、') : '初期値Excelを準備しました。'}</p><button class="btn btn-secondary" id="md-export-download">ダウンロード</button>` : ''}</section>`;
      this.ctx.app.innerHTML = `<div class="app-shell">${this.ctx.sidebarHtml(this.mode)}<div class="app-frame">${this.ctx.headerHtml(title)}<main class="app-main"><p role="status" class="muted">${e(this.message)}</p>${sections}</main></div></div>`;
      this.ctx.bindChrome(); this.bind();
    },
    bind() {
      document.getElementById('md-convert')?.addEventListener('click', () => this.action(async () => { const file = document.getElementById('md-source').files[0]; if (!file) throw new Error('原本Excelを選択してください'); const form = new FormData(); form.append('file', file); this.prepared = await this.request('/api/master-data-preparations', { method: 'POST', body: form }); this.message = '変換が完了しました。30分以内に一度だけダウンロードしてください。'; }));
      document.getElementById('md-download')?.addEventListener('click', () => { this.download(`/api/master-data-preparations/${encodeURIComponent(this.prepared.download_token)}.xlsx`); this.prepared.download_token = null; this.message = '編集用Excelをダウンロードしました。'; this.render(); });
      document.getElementById('md-preview')?.addEventListener('click', () => this.action(async () => { const file = document.getElementById('md-completed').files[0]; if (!file) throw new Error('完成Excelを選択してください'); const form = new FormData(); form.append('file', file); this.preview = await this.request('/api/master-data-imports/preview', { method: 'POST', body: form }); this.message = '検証が完了しました。内容を確認して登録してください。'; }));
      document.getElementById('md-errors')?.addEventListener('click', () => { this.download(`/api/master-data-imports/${encodeURIComponent(this.preview.error_download_token)}/errors.xlsx`); this.preview.error_download_token = null; this.render(); });
      document.getElementById('md-commit')?.addEventListener('click', () => this.action(async () => { if (!window.confirm('プレビューで正常と判定された行を登録します。よろしいですか？')) return; const result = await this.request(`/api/master-data-imports/${encodeURIComponent(this.preview.preview_token)}/commit`, { method: 'POST', body: '{}' }); this.message = `登録しました（新規 ${result.created}、更新 ${result.updated}、変更なし ${result.unchanged}、除外 ${result.skipped}）。`; this.preview = null; }));
      document.getElementById('md-export')?.addEventListener('click', () => this.action(async()=>{ this.exported=await this.request(this.mode==='db_export'?'/api/db-exports':'/api/master-data-exports',{method:'POST',body:'{}'}); this.message='Excelを準備しました。30分以内にダウンロードしてください。'; }));
      document.getElementById('md-export-download')?.addEventListener('click',()=>{this.download(`/api/${this.mode==='db_export'?'db-exports':'master-data-exports'}/${encodeURIComponent(this.exported.download_token)}.xlsx`);this.exported=null;this.message='Excelをダウンロードしました。';this.render();});
      document.getElementById('md-restore-preview')?.addEventListener('click',()=>this.action(async()=>{const file=document.getElementById('md-restore-source').files[0];if(!file)throw new Error('初期値Excelを選択してください');const form=new FormData();form.append('file',file);this.restore=await this.request('/api/foundation-master-restores/preview',{method:'POST',body:form});this.message='差分を確認し、復旧する行だけ選択してください。';}));
      document.getElementById('md-restore-commit')?.addEventListener('click',()=>this.action(async()=>{const selected=[...document.querySelectorAll('[data-restore-key]:checked')].map(el=>el.dataset.restoreKey);if(!selected.length)throw new Error('復旧する行を選択してください');if(!window.confirm(`選択した ${selected.length} 行を初期値で復旧します。よろしいですか？`))return;const result=await this.request(`/api/foundation-master-restores/${encodeURIComponent(this.restore.preview_token)}/commit`,{method:'POST',body:JSON.stringify({selected_keys:selected})});this.restore=null;this.message=`復旧しました（新規 ${result.created}、更新 ${result.updated}）。`;}));
    },
  };
})();
