(() => {
  const ui=Object.create(window.LinksInvoices);
  Object.assign(ui,{
    kind:'payment',
    async open(ctx){this.ctx=ctx;this.kit=window.LinksFeatureKit.createFeatureKit(ctx);this.ym=this.kit.currentYearMonth();this.filters={q:'',closing:'',status:''};await this.list();},
    async list(message=''){
      this.ctx.renderLoading();const [targets,rows]=await Promise.all([this.ctx.api(`/api/payments/targets?target_year_month=${encodeURIComponent(this.ym)}`),this.ctx.api(`/api/payments?target_year_month=${encodeURIComponent(this.ym)}`)]);if(!targets.res.ok)return this.error(targets.data?.message);this.targets=targets.data.targets||[];
      const visible=this.targets.filter(x=>{const text=`${x.partner_id} ${x.partner_name||''} ${(x.projects||[]).map(p=>p.project_id).join(' ')}`.toLowerCase();return(!this.filters.q||text.includes(this.filters.q.toLowerCase()))&&(!this.filters.closing||String(x.closing_date||'')===this.filters.closing);});
      const todo=visible.map((x,i)=>{const available=x.target_status==='available';const state=x.settlement_id?`<button class="btn btn-ghost btn-small" data-open-target="${x.settlement_id}">${this.status(x.target_status)}</button>`:available?`<button class="btn btn-small" data-draft="${i}">支払可能</button>`:`<span class="status-badge">${this.status(x.target_status)}</span>`;return `<tr><td><input type="checkbox" data-payment-select="${i}" data-key="${x.partner_id}:${x.closing_date}" ${available?'':'disabled'}></td><td>${this.ctx.escapeHtml(x.partner_name||'-')}</td><td>#${x.project_id} ${this.ctx.escapeHtml(x.project_name||'')}</td><td>${x.closing_date==='end'?'末日':`${this.ctx.escapeHtml(x.closing_date||'-')}日`}</td><td class="num">${this.money(x.gross_amount)}</td><td class="num"><strong>${this.money(x.final_transfer_amount)}</strong></td><td>${state}</td></tr>`;}).join('');
      const issued=(rows.data?.payments||[]).filter(x=>!this.filters.status||x.settlement_status===this.filters.status).map(x=>`<tr><td>#${x.payment_id}</td><td>${this.ctx.escapeHtml(x.partner_name||x.partner_id)}</td><td class="num">${this.money(x.gross_amount)}</td><td class="num">${this.money(x.final_transfer_amount)}</td><td><span class="status-badge status-${x.settlement_status}">${this.status(x.settlement_status)}</span></td><td><button class="btn btn-ghost btn-small" data-open="${x.payment_id}">開く</button></td></tr>`).join('');
      this.ctx.app.innerHTML=this.kit.shell('支払管理',`<section class="panel">${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}${this.kit.monthNavigatorHtml(this.ym,'payment-month')}<div class="settlement-filters"><input id="payment-q" placeholder="パートナー・案件を検索" value="${this.ctx.escapeHtml(this.filters.q)}"><button id="payment-filter" class="btn btn-secondary">絞り込み</button></div><div class="section-title-row"><h3>月次支払対象案件</h3><button id="create-payment-selected" class="btn">選択案件から支払明細を作成</button></div><p class="muted">案件は状態にかかわらず表示します。締日は案件設定を自動適用します。</p><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>選択</th><th>パートナー</th><th>案件</th><th>締日</th><th>支払総額</th><th>予定振込額</th><th>状態</th></tr></thead><tbody>${todo||'<tr><td colspan="7">案件がありません</td></tr>'}</tbody></table></div><div class="section-title-row"><h3>作成済み支払</h3><select id="payment-status"><option value="">全状態</option>${['draft','sales_reviewed','finalized','cancelled'].map(v=>`<option value="${v}" ${this.filters.status===v?'selected':''}>${this.status(v)}</option>`).join('')}</select></div><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>No</th><th>パートナー</th><th>支払総額</th><th>最終振込額</th><th>状態</th><th>操作</th></tr></thead><tbody>${issued||'<tr><td colspan="6">作成済み支払はありません</td></tr>'}</tbody></table></div></section>`,{wide:true});
      this.kit.bindShell();this.kit.bindMonthNavigator('payment-month',()=>this.ym,v=>{this.ym=v;},()=>this.list());document.getElementById('payment-filter').onclick=()=>{this.filters.q=document.getElementById('payment-q').value.trim();this.list();};document.getElementById('payment-status').onchange=e=>{this.filters.status=e.target.value;this.list();};document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>this.draft([this.targets[Number(b.dataset.draft)]]));document.querySelectorAll('[data-open],[data-open-target]').forEach(b=>b.onclick=()=>this.detail(Number(b.dataset.open||b.dataset.openTarget)));document.getElementById('create-payment-selected').onclick=()=>{const checked=[...document.querySelectorAll('[data-payment-select]:checked')];if(!checked.length)return window.alert('支払対象を選択してください');if(new Set(checked.map(x=>x.dataset.key)).size!==1)return window.alert('パートナーと締日が同じ案件だけをまとめられます');this.draft(checked.map(x=>this.targets[Number(x.dataset.paymentSelect)]));};
    },
    async draft(targets){const first=targets[0],salary=window.confirm('給与明細書も発行しますか？'),reportIds=[...new Set(targets.flatMap(x=>x.report_ids||[]))];const r=await this.ctx.api('/api/settlements/payment/drafts',{method:'POST',body:JSON.stringify({target_year_month:this.ym,partner_id:first.partner_id,daily_report_ids:reportIds,issue_salary_statement:salary})});if(!r.res.ok)return window.alert(r.data?.message||'下書き作成に失敗しました');this.detail(r.data.settlement_id);},
    async detail(id){
      this.ctx.renderLoading();const r=await this.ctx.api(`/api/settlements/payment/${id}`);if(!r.res.ok)return this.error(r.data?.message,()=>this.list());
      const {settlement:s,workflow:w,lines=[],documents=[],audit_logs=[]}=r.data,editable=w?.status==='draft';this.currentLines=lines;
      const work=lines.filter(x=>['work','adjustment'].includes(x.line_type)),deductions=lines.filter(x=>!['work','adjustment'].includes(x.line_type));
      const docs=documents.map(x=>`<li>${this.ctx.escapeHtml(x.document_number)}（${x.status==='issued'?'発行済み':'取消済み'}）${x.status==='issued'?` <a href="/api/settlements/documents/${x.settlement_document_id}/download">PDF</a>`:''}</li>`).join('');
      const history=[...(w?.cancellation_reason?[{acted_at:w.cancelled_at,action_code:'取消',reason:w.cancellation_reason}]:[]),...audit_logs].slice(0,20).map(x=>`<tr><td>${this.ctx.escapeHtml(x.acted_at||'')}</td><td>${this.ctx.escapeHtml(x.action_code||'')}</td><td>${this.ctx.escapeHtml(x.reason||'摘要のみ変更')}</td></tr>`).join('');
      const card=(label,value)=>`<div><span>${label}</span><strong>${this.money(value)}</strong></div>`;
      const actions=`${w?.status==='draft'?'<button id="review" class="btn">営業確認</button>':''}${w?.status==='sales_reviewed'?'<select id="cycle"></select><button id="finalize" class="btn">最終確定・PDF発行</button>':''}${['draft','sales_reviewed','finalized'].includes(w?.status)?'<button id="cancel" class="btn btn-ghost">取消</button>':''}${w?.status==='finalized'?'<button id="correct" class="btn btn-ghost">実行済み訂正</button>':''}<button id="back" class="btn btn-ghost">一覧へ</button>`;
      this.ctx.app.innerHTML=this.kit.shell(`支払明細 #${id}`,`<section class="panel settlement-editor"><div class="document-preview"><div class="document-preview-head"><strong>パートナー #${s.partner_id} 様</strong><div><h2>${s.target_year_month}度支払明細書</h2><p>状態：${this.status(w?.status)}</p></div></div><div class="settlement-summary">${card('支払総額',s.gross_amount)}${card('前払控除',s.advance_deduction_amount)}${card('前払手数料',s.transfer_fee_deduction_amount)}${card('会費・手数料等',Number(s.office_fee_amount||0)+Number(s.safety_fee_amount||0))}${card('調整額',s.other_adjustment_amount)}${card('最終振込額',s.final_transfer_amount)}</div><h3>支払（支給）明細</h3><div class="table-wrap"><table class="document-lines"><thead><tr><th>No.</th><th>摘要</th><th>単価</th><th>数量</th><th>金額</th><th>税区分</th>${editable?'<th>編集</th>':''}</tr></thead><tbody>${this.lineRows(work,editable)||'<tr><td colspan="7">支給明細がありません</td></tr>'}</tbody></table></div><h3>控除明細</h3><div class="table-wrap"><table class="document-lines"><thead><tr><th>No.</th><th>摘要</th><th>単価</th><th>数量</th><th>金額</th><th>税区分</th></tr></thead><tbody>${deductions.length?this.lineRows(deductions,false):'<tr><td colspan="6">最終確定時に前払・控除・繰越を適用します</td></tr>'}</tbody></table></div></div>${editable?'<div class="settlement-edit-actions"><button id="add-line" class="btn">＋ 金額明細を追加</button><button id="source-diff" class="btn btn-secondary">日報から再反映</button></div>':''}<h3>PDF帳票</h3><p><a class="btn btn-secondary" target="_blank" href="/api/settlements/payment/${id}/preview">見本PDFイメージを確認</a> <span class="muted">「見本・未発行」の透かし付きです。</span></p><ul>${docs||'<li>正式PDFは最終確定後に発行します</li>'}</ul><details><summary>編集・取消履歴</summary><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>日時</th><th>操作</th><th>理由</th></tr></thead><tbody>${history||'<tr><td colspan="3">履歴はありません</td></tr>'}</tbody></table></div></details><div class="btn-row">${actions}</div></section>`,{wide:true,onBack:()=>this.list()});
      this.kit.bindShell({onBack:()=>this.list()});document.getElementById('back').onclick=()=>this.list();document.querySelectorAll('[data-save-line]').forEach(b=>b.onclick=()=>this.saveLine(id,b));document.querySelectorAll('[data-delete-line]').forEach(b=>b.onclick=()=>this.deleteLine(id,b));document.querySelectorAll('[data-up],[data-down]').forEach(b=>b.onclick=()=>this.moveLine(id,Number(b.dataset.up||b.dataset.down),Boolean(b.dataset.up)));document.getElementById('add-line')?.addEventListener('click',()=>this.addLine(id));document.getElementById('source-diff')?.addEventListener('click',()=>this.showDiff(id));document.getElementById('review')?.addEventListener('click',()=>this.action(`/api/settlements/payment/${id}/sales-review`,{},()=>this.detail(id)));document.getElementById('cancel')?.addEventListener('click',()=>{const reason=window.prompt('取消理由','');if(reason)this.action(`/api/settlements/payment/${id}/cancel`,{reason},()=>this.list('取消しました'));});document.getElementById('correct')?.addEventListener('click',()=>this.correction(id));if(w?.status==='sales_reviewed')this.cycles(id);
    },
    async cycles(id){const r=await this.ctx.api(`/api/cash-management/cycles?target_year_month=${this.ym}`),e=document.getElementById('cycle');if(!e)return;e.innerHTML=(r.data?.cycles||[]).map(x=>`<option value="${x.cash_cycle_id}">${x.cycle_code==='end'?'末日':Number(x.cycle_code)}日回</option>`).join('');document.getElementById('finalize').onclick=()=>this.action(`/api/settlements/payment/${id}/finalize`,{cash_cycle_id:Number(e.value)},()=>this.detail(id));},
    error(message,onBack){this.ctx.app.innerHTML=this.kit.shell('支払管理',`<section class="panel"><p class="error">${this.ctx.escapeHtml(message||'取得に失敗しました')}</p></section>`,{onBack});this.kit.bindShell({onBack});},
  });window.LinksPayments=ui;
})();
