(() => {
  const ui=Object.create(window.LinksInvoices);
  Object.assign(ui,{
    kind:'payment',
    async open(ctx){this.ctx=ctx;this.kit=window.LinksFeatureKit.createFeatureKit(ctx);this.ym=this.kit.currentYearMonth();this.filters={q:'',closing:'',status:''};await this.list();},
    async list(message=''){
      this.ctx.renderLoading();const [targets,rows]=await Promise.all([this.ctx.api(`/api/payments/targets?target_year_month=${encodeURIComponent(this.ym)}`),this.ctx.api(`/api/payments?target_year_month=${encodeURIComponent(this.ym)}`)]);if(!targets.res.ok)return this.error(targets.data?.message);this.targets=targets.data.targets||[];
      const visible=this.targets.filter(x=>{const text=`${x.partner_id} ${x.partner_name||''} ${(x.projects||[]).map(p=>p.project_id).join(' ')}`.toLowerCase();return(!this.filters.q||text.includes(this.filters.q.toLowerCase()))&&(!this.filters.closing||String(x.closing_date||'')===this.filters.closing);});
      const todo=visible.map((x,i)=>`<tr><td>${this.ctx.escapeHtml(x.partner_name||'-')}</td><td>${(x.projects||[]).map(p=>`#${p.project_id}`).join('、')||'-'}</td><td>${x.closing_date==='end'?'末日':`${this.ctx.escapeHtml(x.closing_date||'-')}日`}</td><td class="num">${this.money(x.gross_amount)}円</td><td class="num">${this.money(x.advance_deduction_amount)}円</td><td class="num">${this.money(x.rule_deduction_amount)}円</td><td class="num"><strong>${this.money(x.final_transfer_amount)}円</strong></td><td><button class="btn btn-small" data-draft="${i}">下書き作成</button></td></tr>`).join('');
      const issued=(rows.data?.payments||[]).filter(x=>!this.filters.status||x.settlement_status===this.filters.status).map(x=>`<tr><td>#${x.payment_id}</td><td>${this.ctx.escapeHtml(x.partner_name||x.partner_id)}</td><td class="num">${this.money(x.gross_amount)}円</td><td class="num">${this.money(x.final_transfer_amount)}円</td><td><span class="status-badge status-${x.settlement_status}">${this.status(x.settlement_status)}</span></td><td><button class="btn btn-ghost btn-small" data-open="${x.payment_id}">開く</button></td></tr>`).join('');
      this.ctx.app.innerHTML=this.kit.shell('支払管理',`<section class="panel">${message?`<p class="flash">${this.ctx.escapeHtml(message)}</p>`:''}${this.kit.monthNavigatorHtml(this.ym,'payment-month')}<div class="settlement-filters"><input id="payment-q" placeholder="パートナー・案件を検索" value="${this.ctx.escapeHtml(this.filters.q)}"><select id="payment-closing"><option value="">全締日</option>${['5','10','15','20','25','end'].map(v=>`<option value="${v}" ${this.filters.closing===v?'selected':''}>${v==='end'?'末日':`${v}日`}</option>`).join('')}</select><button id="payment-filter" class="btn btn-secondary">絞り込み</button></div><h3>月次支払対象</h3><p class="muted">支給項目は日別ではなく、案件・単価・項目別に月額集計します。</p><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>パートナー</th><th>対象案件</th><th>締日</th><th>支払総額</th><th>前払控除</th><th>その他控除</th><th>最終振込額</th><th>操作</th></tr></thead><tbody>${todo||'<tr><td colspan="8">支払対象はありません</td></tr>'}</tbody></table></div><div class="section-title-row"><h3>作成済み支払</h3><select id="payment-status"><option value="">全状態</option>${['draft','sales_reviewed','finalized','cancelled'].map(v=>`<option value="${v}" ${this.filters.status===v?'selected':''}>${this.status(v)}</option>`).join('')}</select></div><div class="table-wrap"><table class="data-table data-table-compact"><thead><tr><th>No</th><th>パートナー</th><th>支払総額</th><th>最終振込額</th><th>状態</th><th>操作</th></tr></thead><tbody>${issued||'<tr><td colspan="6">作成済み支払はありません</td></tr>'}</tbody></table></div></section>`,{wide:true});
      this.kit.bindShell();this.kit.bindMonthNavigator('payment-month',()=>this.ym,v=>{this.ym=v;},()=>this.list());document.getElementById('payment-filter').onclick=()=>{this.filters.q=document.getElementById('payment-q').value.trim();this.filters.closing=document.getElementById('payment-closing').value;this.list();};document.getElementById('payment-status').onchange=e=>{this.filters.status=e.target.value;this.list();};document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>this.draft(this.targets[Number(b.dataset.draft)]));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>this.detail(Number(b.dataset.open)));
    },
    async draft(target){const salary=window.confirm('給与明細書も発行しますか？');const r=await this.ctx.api('/api/settlements/payment/drafts',{method:'POST',body:JSON.stringify({target_year_month:this.ym,partner_id:target.partner_id,daily_report_ids:target.report_ids,closing_date:target.closing_date||'end',issue_salary_statement:salary})});if(!r.res.ok)return window.alert(r.data?.message||'下書き作成に失敗しました');this.detail(r.data.settlement_id);},
    async detail(id){this.ctx.renderLoading();const r=await this.ctx.api(`/api/settlements/payment/${id}`);if(!r.res.ok)return this.error(r.data?.message,()=>this.list());const {settlement:s,workflow:w,lines=[],documents=[]}=r.data,editable=w?.status==='draft';this.currentLines=lines;const work=lines.filter(x=>['work','adjustment'].includes(x.line_type)),deductions=lines.filter(x=>!['work','adjustment'].includes(x.line_type));const docs=documents.map(x=>`<li>${this.ctx.escapeHtml(x.document_number)}（${x.status==='issued'?'発行済み':'取消済み'}）${x.status==='issued'?` <a href="/api/settlements/documents/${x.settlement_document_id}/download">PDF</a>`:''}</li>`).join('');const card=(label,value)=>`<div><span>${label}</span><strong>${this.money(value)}円</strong></div>`;
      this.ctx.app.innerHTML=this.kit.shell(`支払明細 #${id}`,`<section class="panel settlement-editor"><div class="document-preview"><div class="document-preview-head"><strong>パートナー #${s.partner_id} 様</strong><div><h2>${s.target_year_month}度支払明細書</h2><p>状態：${this.status(w?.status)}</p></div></div><div class="settlement-summary">${card('支払総額',s.gross_amount)}${card('前払控除',s.advance_deduction_amount)}${card('前払手数料',s.transfer_fee_deduction_amount)}${card('会費・手数料等',Number(s.office_fee_amount||0)+Number(s.safety_fee_amount||0))}${card('調整額',s.other_adjustment_amount)}${card('最終振込額',s.final_transfer_amount)}</div><h3>支払（支給）明細</h3><div class="table-wrap"><table class="document-lines"><thead><tr><th>No.</th><th>摘要</th><th>単価</th><th>数量</th><th>金額</th><th>税区分</th>${editable?'<th>編集</th>':''}</tr></thead><tbody>${this.lineRows(work,editable)||'<tr><td colspan="7">支給明細がありません</td></tr>'}</tbody></table></div><h3>控除明細</h3><div class="table-wrap"><table class="document-lines"><thead><tr><th>No.</th><th>摘要</th><th>単価</th><th>数量</th><th>金額</th><th>税区分</th></tr></thead><tbody>${deductions.length?this.lineRows(deductions,false):'<tr><td colspan="6">最終確定時に前払・控除・繰越を適用します</td></tr>'}</tbody></table></div></div>${editable?'<div class="settlement-edit-actions"><button id="add-line" class="btn">＋ 金額明細を追加</button><button id="source-diff" class="btn btn-secondary">日報から再反映</button></div>':''}<h3>PDF帳票</h3><ul>${docs||'<li>最終確定後に発行します</li>'}</ul><div class="btn-row">${w?.status==='draft'?'<button id="review" class="btn">営業確認</button>':''}${w?.status==='sales_reviewed'?'<select id="cycle"></select><button id="finalize" class="btn">最終確定・PDF発行</button>':''}${w?.status==='finalized'?'<button id="cancel" class="btn btn-ghost">未実行取消</button><button id="correct" class="btn btn-ghost">実行済み訂正</button>':''}<button id="back" class="btn btn-ghost">一覧へ</button></div></section>`,{wide:true,onBack:()=>this.list()});this.kit.bindShell({onBack:()=>this.list()});document.getElementById('back').onclick=()=>this.list();document.querySelectorAll('[data-save-line]').forEach(b=>b.onclick=()=>this.saveLine(id,b));document.querySelectorAll('[data-delete-line]').forEach(b=>b.onclick=()=>this.deleteLine(id,b));document.querySelectorAll('[data-up],[data-down]').forEach(b=>b.onclick=()=>this.moveLine(id,Number(b.dataset.up||b.dataset.down),Boolean(b.dataset.up)));document.getElementById('add-line')?.addEventListener('click',()=>this.addLine(id));document.getElementById('source-diff')?.addEventListener('click',()=>this.showDiff(id));document.getElementById('review')?.addEventListener('click',()=>this.action(`/api/settlements/payment/${id}/sales-review`,{},()=>this.detail(id)));document.getElementById('cancel')?.addEventListener('click',()=>{const reason=window.prompt('取消理由','');if(reason)this.action(`/api/settlements/payment/${id}/cancel`,{reason},()=>this.detail(id));});document.getElementById('correct')?.addEventListener('click',()=>this.correction(id));if(w?.status==='sales_reviewed')this.cycles(id);},
    async cycles(id){const r=await this.ctx.api(`/api/cash-management/cycles?target_year_month=${this.ym}`),e=document.getElementById('cycle');if(!e)return;e.innerHTML=(r.data?.cycles||[]).map(x=>`<option value="${x.cash_cycle_id}">${x.cycle_code==='end'?'末日':Number(x.cycle_code)}日回</option>`).join('');document.getElementById('finalize').onclick=()=>this.action(`/api/settlements/payment/${id}/finalize`,{cash_cycle_id:Number(e.value)},()=>this.detail(id));},
    error(message,onBack){this.ctx.app.innerHTML=this.kit.shell('支払管理',`<section class="panel"><p class="error">${this.ctx.escapeHtml(message||'取得に失敗しました')}</p></section>`,{onBack});this.kit.bindShell({onBack});},
  });window.LinksPayments=ui;
})();
