const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { getPool } = require('../src/db');
const { chromium } = require('playwright');
const base = 'http://127.0.0.1:3000';
const parse = (v) => typeof v === 'string' ? JSON.parse(v) : v;
async function main() {
  assert.match(process.env.DB_NAME || '', /verify$/, '専用匿名検証DBのみ実行可能');
  let cookie = '';
  const api = async (route, body, expected = 200, method = body ? 'POST' : 'GET') => {
    const response = await fetch(base + route, { method, headers: { 'content-type':'application/json', cookie }, ...(body ? { body:JSON.stringify(body) } : {}) });
    if (response.headers.get('set-cookie')) cookie = response.headers.get('set-cookie').split(';')[0];
    const data = await response.json();
    assert.equal(response.status, expected, `${route}: ${JSON.stringify(data)}`);
    return data;
  };
  const pool = getPool();
  let browser;
  try {
    await api('/api/fee-logic', null, 401);
    await api('/api/auth/login', { login_id:process.env.ADMIN_LOGIN_ID, password:process.env.ADMIN_PASSWORD });
    const catalog = await api('/api/fee-logic');
    assert.equal(catalog.masters.filter((m) => m.kind === 'logic').length, 2);
    assert.equal(catalog.masters.filter((m) => m.kind === 'group').length, 4);
    const company = (await api('/api/companies', { company_name:'匿名ロジック検証', billings:[{ billing_name:'本社請求部',billing_print_name:'匿名企業 御中' },{ billing_name:'支店請求部',billing_print_name:'匿名支店 御中' }] }, 201)).company;
    assert.equal(company.billings[0].billing_name, '本社請求部');
    assert.equal(company.billings[0].billing_print_name, '匿名企業 御中');
    const companyId = company.company_id;
    const baseProject = (await api('/api/projects/base', { company_id:companyId,template_name:'匿名基本案件',billing_no:1 },201)).base_project;
    assert.equal(baseProject.billing_no,1);
    assert.equal(baseProject.billing_name,'支店請求部');
    const project = (await api('/api/projects', { company_id:companyId,billing_no:0 },201)).project;
    assert.equal(project.billing_no,0);
    await api('/api/projects', { company_id:companyId,billing_no:999 },400);
    await api('/api/projects', { company_id:companyId,billing_no:1,billing_id:company.billings[0].billing_id },400);
    const price = (await api('/api/price-sets', { company_id:companyId,project_id:project.project_id,price_set_name:'匿名日極',apply_start_date:'2026-01-01',extra_data:{ fee_items:[{ id:'test_daily',name:'通常',weekdays:{ all:true },rows:[{ id:'basic',item_type:'daily_basic',billing:17500,payment:12219 }] }],work_rules:{ standard_minutes:480 },rounding:{ billing:{ amount_stage:'month' },payment:{ amount_stage:'month' } } } },201)).price_set;
    assert.equal(parse(price.extra_data).fee_items[0].logic_group_code,'daily');
    // Re-run only the association SQL inside a rolled-back transaction against an anonymous card.
    const conn = await pool.getConnection();
    try {
      await conn.beginTransaction();
      const sampleExtra = { keep:'unchanged',fee_items:[{ id:'a',rows:[{ item_type:'daily_basic',billing:17 }] },{ id:'b',rows:[{ item_type:'hourly',billing:19 }] },{ id:'c',rows:[{ item_type:'unit',billing:21 }] },{ id:'d',rows:[{ item_type:'distance',billing:23 }] }] };
      await conn.query('UPDATE price_sets SET extra_data=? WHERE price_set_id=?',[JSON.stringify(sampleExtra),price.price_set_id]);
      await conn.query(fs.readFileSync(path.resolve(__dirname,'../../db/migrations/049_bind_fee_logic_groups.sql'),'utf8'));
      const [[saved]] = await conn.query('SELECT extra_data FROM price_sets WHERE price_set_id=?',[price.price_set_id]);
      const extra = parse(saved.extra_data);
      assert.equal(extra.keep,'unchanged');
      assert.deepEqual(extra.fee_items.map((item) => item.logic_group_code),['daily','hourly','quantity','distance']);
      extra.fee_items.forEach((item) => delete item.logic_group_code);
      assert.deepEqual(extra,sampleExtra);
      await conn.rollback();
    } finally { conn.release(); }
    const input = { project_id:project.project_id,work_date:'2026-09-30',start_time:'09:00',end_time:'18:00',break_minutes:60 };
    const before = (await api('/api/daily-reports/preview',input)).preview;
    assert.equal(Number(before.calculated_billing_amount),17500);
    assert.equal(Number(before.calculated_payment_amount),12219);
    const initial = catalog.masters.find((m) => m.code==='multiply').versions[0];
    const nextDate = new Date(Math.max(Date.parse('2026-10-01'),Date.parse(initial.effective_from)+86400000)).toISOString().slice(0,10);
    const candidate = { previous_version:initial.version_no,effective_from:nextDate,reason:'匿名検証の10%変更',definition:{ expression:'quantity * unit_price * 1.1' },samples:[{ quantity:18,unit_price:17500,expected:346500 }] };
    const confirmed = (await api('/api/daily-reports', { ...input,work_date:nextDate,company_id:companyId,target_year_month:nextDate.slice(0,7) },201)).report;
    await pool.query("UPDATE daily_reports SET status='confirmed' WHERE daily_report_id=?",[confirmed.daily_report_id]);
    await api('/api/fee-logic/multiply/preview',candidate);
    await api('/api/fee-logic/multiply/versions',{ ...candidate,samples:[{ quantity:1,unit_price:1,expected:99 }] },422);
    await api('/api/fee-logic/multiply/versions',candidate,201);
    await api('/api/fee-logic/multiply/versions',candidate,409);
    const unchanged = (await api(`/api/daily-reports/${confirmed.daily_report_id}`,{ version:confirmed.version,memo:'確認済み金額を維持' },200,'PUT')).report;
    assert.equal(Number(unchanged.calculated_billing_amount),Number(confirmed.calculated_billing_amount));
    assert.deepEqual(parse(unchanged.calculation_detail),parse(confirmed.calculation_detail));
    const stillBefore = (await api('/api/daily-reports/preview',input)).preview;
    assert.equal(Number(stillBefore.calculated_billing_amount),17500);
    const after = (await api('/api/daily-reports/preview',{ ...input,work_date:nextDate })).preview;
    assert.equal(Number(after.calculated_billing_amount),19250);
    assert.equal(parse(before.calculation_detail).fee_item.logic_group.logics.basic.version_no,1);
    assert.equal(parse(after.calculation_detail).fee_item.logic_group.logics.basic.version_no,initial.version_no+1);
    browser = await chromium.launch({ headless:true,args:['--no-sandbox'] });
    const page = await browser.newPage({ viewport:{ width:1440,height:1000 } });
    const errors = [];
    page.on('pageerror',(error) => errors.push(error.message));
    await page.request.post(base+'/api/auth/login',{ data:{ login_id:process.env.ADMIN_LOGIN_ID,password:process.env.ADMIN_PASSWORD } });
    await page.goto(base,{ waitUntil:'networkidle' });
    await page.locator('[data-nav-feature="projects"]').first().click();
    await page.locator('#project-list-root').waitFor();
    await page.evaluate(async (id) => window.LinksProjects.showProjectDetail(id),project.project_id);
    const picker = page.locator('#project-billing .search-select-input');
    assert.equal(await picker.inputValue(),'0：本社請求部');
    await picker.fill('１');
    await picker.blur();
    assert.equal(await picker.inputValue(),'1：支店請求部');
    assert.equal(await page.locator('#project-billing [name="billing_id"]').inputValue(),String(company.billings[1].billing_id));
    await picker.fill('999');
    assert.equal(await picker.evaluate((el) => el.checkValidity()),false);
    await page.locator('[data-nav-feature="price_sets"]').first().click();
    await page.locator('#price-sets-table').waitFor();
    await page.evaluate(async (id) => window.LinksPriceSets.showDetail(id),price.price_set_id);
    assert.equal(await page.locator('.fee-logic-group').first().inputValue(),'daily');
    await page.locator('[data-nav-feature="master_settings"]').first().click();
    await page.locator('[data-hub="fee-logic"]').click();
    await page.getByRole('heading',{ name:'料金計算ロジック・グループマスター' }).waitFor();
    assert.equal(await page.locator('[data-revise]').count(),2);
    await page.screenshot({ path:'/tmp/fee-logic-master.png',fullPage:true });
    assert.deepEqual(errors,[]);
    const bcrypt = require('bcryptjs');
    const readerId = `fee-reader-${companyId}`;
    await pool.query('INSERT INTO users(login_id,password_hash,display_name,role,roles,is_active) VALUES(?,?,?,?,?,1)',[readerId,await bcrypt.hash('anonymous-test-only',4),'匿名参照者','staff',JSON.stringify(['soumu'])]);
    await api('/api/auth/login',{ login_id:readerId,password:'anonymous-test-only' });
    assert.equal((await api('/api/fee-logic')).can_edit,false);
    await api('/api/fee-logic/multiply/versions',candidate,403);
    console.log(JSON.stringify({ ok:true,api:true,version_boundary:true,billing_no_manual:true,migration_preserves_rates:true,ui_errors:errors.length,company_id:companyId,project_id:project.project_id,price_set_id:price.price_set_id }));
  } finally { if (browser) await browser.close(); await pool.end(); }
}
main().catch((error) => { console.error(error.stack); process.exitCode=1; });
